### PR TITLE
unused payloads

### PR DESCRIPTION
**Pull request by MithrilMan**
removed unused payloads
see #2903

### CODE REVIEW

**Comment by noescape00** [comment]
Please merge if you agree with keeping notfoundpayload. Otherwise remove it and lets discuss.

**Comment by dangershony** [comment]
Looks good to me as well, but I suggest a network sync just in case (testnet is enough)

**Comment by noescape00** [comment]
>but I suggest a network sync just in case 

Imho not needed- none of those payloads were referenced anywhere in our code. 
I've built the solution and found no build errors.

**Comment by bokobza** [comment]
good stuff.

**Pull request merged**
