### PR TITLE
Move Network registrations to Networks class

### PR DESCRIPTION
**Pull request by rowandh**
This is a large diff because networks are referenced everywhere, but there's only two things that have changed:
* Move networks to a different namespace (NetworkDefinitions)
* Move static network registrations to a new class (Networks)

Importantly, this brings static network registrations out of `Network.cs`.

### CODE REVIEW

**Comment by fassadlr** [comment]
@rowandh we are happy to merge but fix your conflicts 👍  Good change!

**Comment by dangershony** [comment]
@rowandh this is priority as its easy and not to block you, so once you resolve conflicts ask us to push immediately, PR looks good.

**Comment by fassadlr** [comment]
@rowandh i fixed this for you 👍 I confirm that all unit and integration tests pass.

**Comment by rowandh** [comment]
@fassadlr thanks for fixing!

**Pull request merged**
