### PR TITLE
Increased log message log level so that the messages are logged with default node configuration

### PR DESCRIPTION
**Pull request by maciejzaleski**
Some important log messages are not being logged with high enough log level making them show only when configuring the node to log at lower levels (i.e. DEBUG, TRACE)

### CODE REVIEW

**Comment by dangershony** [comment]
Perhaps we should have some agreed happy path logging and all the rest are divided to the debug categories?

Currently we have as happy path is `stats, connect, disconnect, stake weight` events.
I probably missed some others.

Things that are unusual should be logged I agree (like rewind, or an exception, the time sync warning, etc...)

**Comment by maciejzaleski** [comment]
The primary purpose of the log is not to look pretty but to help diagnose issues with the code. Currently we don't know why peers disconnect from each other or why the node is not syncing as those log messages are logged at lower levels.

The changes I've made are mainly around the exception cases you shouldn't see any additional log information during normal node operation.

It would be good idea to review changes around P2P as I think we should limit the number of messages there.

**Comment by dangershony** [comment]
> The primary purpose of the log is not to look pretty but to help diagnose issues with the  

I dont think anyone suggested logs should be pretty, rather we refere to a the console become clutted with info. 

>The changes I've made are mainly around the exception cases  

This is fine I agree, if thats the case I will review the PR more thoroughly to give my opinion.
In such cases I'd say we should log many of those as warnings (and not information)

**Comment by fassadlr** [comment]
Closing as we can revisit this in https://github.com/stratisproject/StratisFullNode

**Pull request closed without merging**
