### PR TITLE
[BlockStore] Split BlockStoreLoop #206

### PR DESCRIPTION
**Pull request by fassadlr**
This work here relates to:

https://github.com/stratisproject/StratisBitcoinFullNode/issues/206

I've split the logic of DownloadAndStoreBlocks into 4 logical steps using a successor type pattern. Each "Step" has its own uni tests.  Also, I've renamed various variables to be more user readable and understandable.

### CODE REVIEW

**Comment by bokobza** [comment]
@fassadlr I don't exactly know what happened there but it seems 520 files are included in this release.
I'm going to go out on a limb here and say this was not intentional?

**Comment by fassadlr** [comment]
Hi @bokobza! I know what happened here... I ignored and then re-included the NBitcoin project... in the NStratis folder.

Is the NBitcoin project checked out with the FullNode solution?

**Comment by fassadlr** [comment]
It appears that the NBitcoin project reference was added after my initial download. I suspect this might have been a merge issue as well. Maybe I should close this PR.. re-clone and re-submit the PR with only the relevant changes?

**Comment by dangershony** [comment]
yes @fassadlr close and reclone just your changes if not it will be merge hell

**Pull request closed without merging**
