### PR TITLE
PoAMiner mines for most of turn rather than only once

### PR DESCRIPTION
**Pull request by codingupastorm**
Rather than nodes only mining right on their timestamp, they may have the ability to retry during their turn. They have a window of time during which to mine.

### CODE REVIEW

**Comment by codingupastorm** [comment]
This is still relevant. 

Just waiting for 3.0.6.0 to be all cleaned up and then will test this and the other smart contract changes inside master.

**Comment by fassadlr** [comment]
@codingupastorm Can you perhaps latest from master and give us an update on what we  should do with this PR?

**Comment by codingupastorm** [comment]
Yep! It's worth putting in before any more smart contract performance testing happens

**Comment by fassadlr** [comment]
@codingupastorm awesome! I assume needs to go to 3.0.8 as well?

**Pull request merged**
