### PR TITLE
Improved console text alignment for the node stats

### PR DESCRIPTION
**Pull request by noescape00**
It was just a bit annoying to see the wrong padding.

stats - copy

### CODE REVIEW

**Comment by bokobza** [comment]
I don't really see what's "wrong" about the previous padding. 🤔 
All I can see here is that you've made the text a bit more condensed. Is that right, or have I missed something?

**Comment by noescape00** [comment]
@bokobza the lines that have hashes in them were too long for the previous formatting so that caused splitting so the leftover of the hash would go to the next line. 

34082819-c47d3996-e376-11e7-976f-a519ba5b069f

Ofc this is only true for the default console settings (lines are 80 characters long) for both linux and windows.

**Comment by Aprogiena** [comment]
is anyone using console in default?

**Comment by D3m0nKingx** [comment]
As in standard terminal settings? for the most part I keep mine at default, and just adjust the height/width of the window with the cursor to see the output. Also I can zoom out as well in the terminal (dunno if that's smth doable in windows tho).

**Comment by bokobza** [comment]
I use cmder, which is really cool.

**Comment by bokobza** [comment]
but I'm happy for this to be in.

**Pull request merged**
