### PR TITLE
[RPC] Changed "verbose" parameter to boolean

### PR DESCRIPTION
**Pull request by fenix2222**
Changed parameter type to be boolean to be inline with bitcoin RPC

### CODE REVIEW

**Comment by fassadlr** [comment]
@fenix2222 there are some integration tests failing :)

**Comment by fenix2222** [comment]
> @fenix2222 there are some integration tests failing :)

Linux and Mac are fine? I can see windows failing

**Comment by fassadlr** [comment]
@fenix2222 Linux and Mac build doesnt run the integrationt tests. Have a look at the tests that are failing on CI.

**Comment by fenix2222** [comment]
> @fenix2222 Linux and Mac build doesnt run the integrationt tests. Have a look at the tests that are failing on CI.

Yeah, already found it, I will push a fix tomorrow

**Comment by fenix2222** [comment]
@fassadlr that should be good to go now

**Comment by zeptin** [comment]
Note that bitcoind has backwards-compatibility code to accept either boolean or numeric arguments for this RPC and others. 

```
    // Accept either a bool (true) or a num (>=1) to indicate verbose output.
    bool fVerbose = false;
    if (!request.params[1].isNull()) {
        fVerbose = request.params[1].isNum() ? (request.params[1].get_int() != 0) : request.params[1].get_bool();
    }
```

stratisX does the following:

```
    bool fVerbose = false;
    if (params.size() > 1)
        fVerbose = (params[1].get_int() != 0);
```

So my opinion is that both variants should be accepted.

**Comment by fenix2222** [comment]
My fork got reset, I have to redo this PR :(

**Comment by MithrilMan** [comment]
just to somewhat confirm what @zeptin said

I'm doing performance tests on RPC and I'm comparing X to SBFN and in my tries I was passing true/false by mistake, and SBFN accepted it while X node was complaining

e.g. this batch call
```
[{"method":"getrawtransaction","params":["69130e612c49b3da86859c10387c309e6949038e88c1e6cb4ab149a458e3fadc",false],"id":0},{"method":"getrawtransaction","params":["69130e612c49b3da86859c10387c309e6949038e88c1e6cb4ab149a458e3fadc",false],"id":1},{"method":"getrawtransaction","params":["69130e612c49b3da86859c10387c309e6949038e88c1e6cb4ab149a458e3fadc",false],"id":2},{"method":"getrawtransaction","params":["69130e612c49b3da86859c10387c309e6949038e88c1e6cb4ab149a458e3fadc",false],"id":3},{"method":"getrawtransaction","params":["69130e612c49b3da86859c10387c309e6949038e88c1e6cb4ab149a458e3fadc",false],"id":4},{"method":"getrawtransaction","params":["69130e612c49b3da86859c10387c309e6949038e88c1e6cb4ab149a458e3fadc",false],"id":5},{"method":"getrawtransaction","params":["69130e612c49b3da86859c10387c309e6949038e88c1e6cb4ab149a458e3fadc",false],"id":6},{"method":"getrawtransaction","params":["69130e612c49b3da86859c10387c309e6949038e88c1e6cb4ab149a458e3fadc",false],"id":7},{"method":"getrawtransaction","params":["69130e612c49b3da86859c10387c309e6949038e88c1e6cb4ab149a458e3fadc",false],"id":8},{"method":"getrawtransaction","params":["69130e612c49b3da86859c10387c309e6949038e88c1e6cb4ab149a458e3fadc",false],"id":9}]
```

produced this on X
```
[OK]: [{"result":null,"error":{"code":-1,"message":"value is type bool, expected int"},"id":0},{"result":null,"error":{"code":-1,"message":"value is type bool, expected int"},"id":1},{"result":null,"error":{"code":-1,"message":"value is type bool, expected int"},"id":2},{"result":null,"error":{"code":-1,"message":"value is type bool, expected int"},"id":3},{"result":null,"error":{"code":-1,"message":"value is type bool, expected int"},"id":4},{"result":null,"error":{"code":-1,"message":"value is type bool, expected int"},"id":5},{"result":null,"error":{"code":-1,"message":"value is type bool, expected int"},"id":6},{"result":null,"error":{"code":-1,"message":"value is type bool, expected int"},"id":7},{"result":null,"error":{"code":-1,"message":"value is type bool, expected int"},"id":8},{"result":null,"error":{"code":-1,"message":"value is type bool, expected int"},"id":9}]
```

and this on SBFN
```
[OK]: [{"result":"01000000e0bb775c010000000000000000000000000000000000000000000000000000000000000000ffffffff0402510700ffffffff0100000000000000000000000000","id":0,"error":null},{"result":"01000000e0bb775c010000000000000000000000000000000000000000000000000000000000000000ffffffff0402510700ffffffff0100000000000000000000000000","id":1,"error":null},{"result":"01000000e0bb775c010000000000000000000000000000000000000000000000000000000000000000ffffffff0402510700ffffffff0100000000000000000000000000","id":2,"error":null},{"result":"01000000e0bb775c010000000000000000000000000000000000000000000000000000000000000000ffffffff0402510700ffffffff0100000000000000000000000000","id":3,"error":null},{"result":"01000000e0bb775c010000000000000000000000000000000000000000000000000000000000000000ffffffff0402510700ffffffff0100000000000000000000000000","id":4,"error":null},{"result":"01000000e0bb775c010000000000000000000000000000000000000000000000000000000000000000ffffffff0402510700ffffffff0100000000000000000000000000","id":5,"error":null},{"result":"01000000e0bb775c010000000000000000000000000000000000000000000000000000000000000000ffffffff0402510700ffffffff0100000000000000000000000000","id":6,"error":null},{"result":"01000000e0bb775c010000000000000000000000000000000000000000000000000000000000000000ffffffff0402510700ffffffff0100000000000000000000000000","id":7,"error":null},{"result":"01000000e0bb775c010000000000000000000000000000000000000000000000000000000000000000ffffffff0402510700ffffffff0100000000000000000000000000","id":8,"error":null},{"result":"01000000e0bb775c010000000000000000000000000000000000000000000000000000000000000000ffffffff0402510700ffffffff0100000000000000000000000000","id":9,"error":null}]
```

**Comment by fenix2222** [comment]
I am just wondering what would be the best approach for this, currently RPC uses a controller with a strongly typed int parameter? We could use parameter or action overload or maybe dynamic?

**Comment by MithrilMan** [comment]
we could have a json converter that attempt to convert any integer to boolean, this should solve the problem

Basically if the model requires a bool, it should accept an int and convert it to bool

**Comment by MithrilMan** [comment]
Actually I think this already works as I said because I fixed my tests and if I pass 1 or 0 it works fine

**Comment by fenix2222** [comment]
It works if you pass 1 or 0, but it doesn’t work when you pass true or false, bitcoin supports both

**Comment by MithrilMan** [comment]
look my attached snippets above, I was passing true/false previously and SBFN was working fine

**Comment by MithrilMan** [comment]
{"method":"getrawtransaction","params":["69130e612c49b3da86859c10387c309e6949038e88c1e6cb4ab149a458e3fadc",false],"id":1}

X fails, SBFN pass

**Comment by fenix2222** [comment]
Do you actually get a verbose response? The issue is that it just uses verbose=0 whether you pass true or false

**Comment by MithrilMan** [comment]
ok got you, I was testing with 0 and didn't noticed that it doesn't returns the json if you pass true

**Comment by MithrilMan** [comment]
like stated on bitcoin RPC documentation
https://bitcoincore.org/en/doc/0.18.0/rpc/rawtransactions/getrawtransaction/

verbose is a boolean, so I'd declare it as a boolean in our model and have the converter accept integer representation of 1/0

Probably what you already did but the code isn't here to confirm that :D

**Comment by MithrilMan** [comment]
linking an old related bitcoin issue: https://github.com/bitcoin/bitcoin/issues/9802

**Comment by MithrilMan** [comment]
from my understanding verbosity was accepted as int because they wanted to have different level of verbosity at first, while actually it's a toggle

**Pull request closed without merging**
