### PR TITLE
Cleanup block definitions

### PR DESCRIPTION
**Pull request by fassadlr**
The reviewer can review by commit.

Changes:

1 > Remove unused `BlockTemplate.CoinbaseCommitment`
2 > Remove unused `BlockTemplate.TxSigOpsCost`
3 > Remove unused `BlockTemplate.VTxFees`
4 > Move `CompareModifiedEntry`  to own file
5 > Move `CompareTxIterByAncestorCount`  to own file
6 > Move `TxMemPoolModifiedEntry` to own file
7 > Remove abstract `BlockDefinition.OnTestBlockValidity()` as its only used in `PowBlockDefinition`
8> Rename abstract `OnUpdateHeaders` to `UpdateHeaders`

### CODE REVIEW

**Comment by fassadlr** [comment]
All unit tests pass and integration tests.

**Comment by fassadlr** [comment]
I can confirm that testnet has synced and staking still works as per normal.

**Comment by dangershony** [comment]
Tomorrow I will do this first thing

**Comment by dangershony** [comment]
I know sigop is not used but I would suggest to keep it there and create an issue to activate it.
We wont min on bitcoin and stratis does not have full blocks (yet) also due to shorter block time.

**Pull request merged**
