### PR TITLE
[FS] Fix ModelState Invalid

### PR DESCRIPTION
**Pull request by quantumagi**
See https://dev.azure.com/Stratisplatformuk/StratisBitcoinFullNode/_workitems/edit/4008.

### CODE REVIEW

**Comment by quantumagi** [comment]
The followings tests have been performed:
- Confirmed that swagger is still returning the expected endpoints across application parts.
- Did spot-checks to ensure the API can still be called.
- The help ("--help") is still working as expected.

**Comment by MithrilMan** [comment]
I don't think this will solve the problem and tests aren't enough to cover the issue (race condition where multiple requests were performed at the same time on the same controller/endpoint)

from my findings, it was ok to call AddControllersAsServices, we just needed to remove every explicit controller registration we had, because they were registering controller using AddSingleton while it should be AddTransient.

**Comment by codingupastorm** [comment]
Agreed with @MithrilMan , try using `AddTransient` @quantumagi ?

**Comment by quantumagi** [comment]
@MithrilMan , @codingupastorm . I've added a test case. Try running the test case with and without the change to confirm that it does indeed solve the issue.

**Comment by MithrilMan** [comment]
As long as controller is registered using AddSingleton it's going to have race conditions.
That test isn't going to trigger it so easily because the error is during the check of ModelState, that's very fast to execute and even parallelizing doesn't mean you hit the case.

If you want to test it properly, a way could be to have an endpoint that loop running lot of ModelState checks in his body, and then parallelize those calls, otherwise the chance you are running into the race condition is unlikely to happen

**Comment by codingupastorm** [comment]
@MithrilMan this is not the case. 

By removing this call, yes _an instance_ of the controllers is injected anywhere in the nodes where needed, but when hitting the API, a new instance is created every time. 

The `AddSingleton` methods aren't what enable the controllers to be hit via the API. It actually happens via some magic.

Check out @quantumagi's other PR, #3803

**Comment by MithrilMan** [comment]
if "The AddSingleton methods aren't what enable the controllers to be hit via the API" is true, then what's the reason of register controllers at all?
in the issue on our board I screenshotted a doc that explain "the magic", I can find reference to it if needed
Maybe what you refers to as "magic" is how MVC works by default and by using AddApplicationPart
https://docs.microsoft.com/it-it/aspnet/core/mvc/advanced/app-parts?view=aspnetcore-2.2

also note, from the doc:
> By default MVC will search the dependency tree and find controllers (even in other assemblies). To load an arbitrary assembly (for instance, from a plugin that isn't referenced at compile time), you can use an application part.

What I'm not sure if the call of "AddSingleton" was overriding the default "AddTransient"
I'd still do the test as I proposed above to test that these don't have race conditions (the submitted test actually isn't useful)

**Comment by MithrilMan** [comment]
here the link to the article where everything is explained and that I referenced to:
https://andrewlock.net/controller-activation-and-dependency-injection-in-asp-net-core-mvc/

**Comment by codingupastorm** [comment]
The test definitely works, if you try running it before and after the change you can see that:

- After the change, it's a different instance every time, but the same before.
- After the change, the test passes.

**Comment by MithrilMan** [comment]
@codingupastorm 

A proper test would ensure that the right condition is asserted and it should work on any machine configuration, not working only on some setups: e.g. what happens if the machine you are running tests on only allows a couple of multiple parallel executions?
I mean tests shouldn't be machine dependent https://stackoverflow.com/a/16938720/1716620

I may be wrong, I can't now check properly (will do later) but can you tell me where the test checks if the instance is the same or not because I don't see it and it should really be the condition to check for the test: ensuring that controller is instantiated per-request and not singleton, isn't it?

This exception was subtle and hard to reproduce, this is why we should test the problem and not the possible causes, imo.

**Comment by quantumagi** [comment]
The right condition to test is to ensure that multiple calls don't share the same `ModelState` - i.e. one call does not pollute the `ModelState` of another. The test is effective in doing that, which also corresponds to the original reported issue. If a machine only allows one thread then it is irreleveant. If it allows more than one then the test will eventually show up the issue.

**Comment by MithrilMan** [comment]
@quantumagi I still think the test doesn't check it explicitly but relay on the expected behavior
anyway let me recap the problem and why this change fixes the problem even if there are refuses in code (that may be fixed by the other PR, I still have to review it)

Basically by default the DefaultControllerActivator doesn't attempt to resolve the Controller instance from the DI container itself but only the Controller's dependencies.

using AddControllersAsServices like we were doing, caused the controllerActivator to be changed to ServiceBasedControllerActivator and this causes controllers to be loaded directly from the DI container.

Note that AddControllersAsServices  register controllers too if they weren't already registered, using Transient scope.
The problem was that we were already registering the services explicitly using the AddSingleton, this is why we had the bugs reported.

So the problem can be fixed in 2 ways:
1 - removing AddControllersAsServices  call and removing all explicit Controller registration because are ignored anyway by DefaultControllerActivator

2 - removing all all explicit Controller registration (this way controllers will be registered by AddControllersAsServices  as Transient and the DI will be used to serve controller instance)

This PR does half the 1st step, I presume the other PR fixes the rest, anyway the easier and safer solution would have been probably the 2nd (it depends if we need controllers to be instantiated by the DI in some case, e.g. if we have a class that need a reference to a controller but I don't think we need)

**Comment by fassadlr** [comment]
@quantumagi Is there really any point to this PR considering #3803 ?

**Comment by fassadlr** [comment]
Merge when build passes 👍

**Comment by fassadlr** [comment]
@quantumagi got this error in the tests:

`System.InvalidOperationException : The Stratis.Bitcoin.Features.Wallet.Controllers.WalletController service is not supported`

**Pull request merged**
