### PR TITLE
RPC getpeerinfo

### PR DESCRIPTION
**Pull request by mikedennis**
Initial implementation of RPC getpeerinfo. Not all RPC fields are populated.

### CODE REVIEW

**Comment by bokobza** [comment]
I'll take this one

**Comment by bokobza** [comment]
@mikedennis hi mate, is there any task for this on the Trello?

**Comment by mikedennis** [comment]
@bokobza It's in backlog. I can only read in trello with my account so can't move anything.

**Comment by mikedennis** [comment]
@bokobza Closing this out, going to recreate this PR to get rid of the NStratis git issues

**Pull request closed without merging**
