### PR TITLE
Fix test case SBFNMinesTransaction_XSyncs

### PR DESCRIPTION
**Pull request by quantumagi**
This fixes a currently skipped test case which was awaiting issue 2468.

May depend on a newer StratisX as per:

https://github.com/stratisproject/StratisBitcoinFullNode/issues/2468#issuecomment-442442549

See https://stratisplatformuk.visualstudio.com/StratisBitcoinFullNode/_workitems/edit/4171.

### CODE REVIEW

**Comment by quantumagi** [comment]
The existing code was re-using the same cancellation token. This is not a good idea as illustrated by the fact that the short delay token was expiring even before it was used.

**Comment by quantumagi** [comment]
This code will not work with the StratisX version found in `...\StratisBitcoinFullNode\src\External libs\StratisX\2.0.0.5\Windows` . The latest code will have to be compiled and included with this PR.

**Comment by dangershony** [comment]
@dev0tion FYI

**Comment by fassadlr** [comment]
@quantumagi `SBFNMinesTransaction_XSyncs` is still failing the build?

**Comment by quantumagi** [comment]
@fassadlr , ?

**Comment by zeptin** [comment]
An updated build of stratisX (specifically, `stratisd.exe`) is needed

**Comment by fassadlr** [comment]
Ahh my apologies @quantumagi !

**Comment by fassadlr** [comment]
@quantumagi what are doing with this PR? can we get StratisD updated or can we close this?

**Pull request closed without merging**
