### PR TITLE
Check a trx is empty for POS on the mempool

### PR DESCRIPTION
**Pull request by dangershony**

### CODE REVIEW

**Comment by dangershony** [comment]
@Aprogiena just a quick glance

**Comment by Aprogiena** [comment]
Looks okay, there is typo in a comment but that's.only to do, so that's fine. Then there is this unrelated removal of a method, but if tests are okay with that it should be okay. And yes the factoring is needed there, so this is rather quick fix, but hopefully okay

**Comment by dangershony** [comment]
>Then there is this unrelated removal of a method
Yeah it broke the tests as did not set root folder, it was suppose to be picked by @jeremy change, but its more correct anyway to call correct regtest network.

**Comment by jeremy** [comment]
s/jeremy/bokobza 😘

**Pull request merged**
