### PR TITLE
Refactor consensus rules to support dependency injection

### PR DESCRIPTION
**Pull request by rowandh**
Currently, consensus rules have dependencies but these are hidden by dumping them on `rule.Parent` and using this as a kind of service locator. The goal of this PR is to move us towards allowing rules to have their dependencies injected via the constructor.

It also fixes some oddities with our current approach, like needing to call `Register` after creating instances of `ConsensusRuleEngine`, having mutable lists of rules, and having to call `Initialize` methods on rules before they can be used.

The initial motivation is that we have smart contract rules with external dependencies that we want to provide in a configurable way (ie. without modifying ConsensusRuleEngine).

Changes:
* Modifies rule registrations to behave as rule factories
* Adds a `RuleContainer` which contains the concrete instances of rules created by rule registrations
* Removes the need to call `Register` on `ConsensusRuleEngine` instances. This functionality is instead performed whenever rules are accessed for the first time, or whenever the rule registration instance is changed (only required for tests). Once all rules have their dependencies DI'd, this will no longer be necessary.
* Removes rules from `Consensus`
* Demonstrates dependency injection for two rules, `ProvenHeaderCoinstakeRule` (eef9124) and `BitcoinActivationRule` (611f34f)

Future work:
There are still many rules that need to be modified to use DI. This work does not all need to be done at the same time and can be separated into several smaller PRs. Happy to start on this too, but wanted to get confirmation on the approach first.

### CODE REVIEW

**Comment by rowandh** [comment]
@noescape00 as per discussion on Slack. Consensus rules are copied onto `Consensus` and then almost immediately copied off. It just behaves as a temporary container. These changes fix that, and would allow us to remove the empty interfaces for rules.

**Comment by dangershony** [comment]
This is still on my list to review 👍

**Comment by dangershony** [comment]
Due to this issue 
https://github.com/stratisproject/StratisBitcoinFullNode/issues/3487#issuecomment-481014071
And the few PRs that are taking place to refactor rules I suggest we close this one @rowandh ?

**Comment by rowandh** [comment]
Closing for now but still interested in revisiting this.

**Pull request closed without merging**
