### PR TITLE
GetData test

### PR DESCRIPTION
**Pull request by dangershony**

### CODE REVIEW

**Comment by dangershony** [comment]
@NicolasDorier FYI

**Comment by NicolasDorier** [comment]
I already did this test, here you are testing a Stratis node is synching on a Core node.

What you must do with what you did is the reverse. Checking a Core node can sync on a Stratis node.

**Comment by dangershony** [comment]
I only found the test CanStratisSyncFromCore() 
Also the getdata payload is required for two stratis nodes to sync right (which is only now implemented)?

**Comment by dangershony** [comment]
I would prefer to make a test CanCoreSyncFromStratis() and CanStratisSyncFromStratis()
But we should then add specific BlockStoreBehavior tests, this will be hard as the Node object will need to be mocked.
Have you ever used moq framework (or nsabstitute)?

**Comment by NicolasDorier** [comment]
@dangershony no need of mock. Look the tests, you can popup a normal stratis fullnode OR a core node.

**Pull request merged**
