### PR TITLE
[FS] Move sidechains code in with history

### PR DESCRIPTION
**Pull request by codingupastorm**
Anyone know how we can disable the CI for sidechains tests until we stabilise them?

### CODE REVIEW

**Comment by bokobza** [comment]
Excellent stuff.
Let me try something to exclude the failing tests.

**Comment by codingupastorm** [comment]
Cool thanks @bokobza, they should all pass but many are inconsistent, so if there's a way we can blacklist the whole namespace that would be ace.

**Also, whoever merges, make sure we do a 'merge with history'** :)

**Comment by bokobza** [comment]
We should probably wait for the release to move this in. We can then ignore the failures and merge it, as long as the first thing we do is fix/skip the offending tests.

**Comment by codingupastorm** [comment]
Cool no worries I'll Skip all of the offending tests in the meanwhile

**Comment by codingupastorm** [comment]
Opening from a branch within this repo, so we can PR changes between us in the meantime.

**Pull request closed without merging**
