### PR TITLE
Add ActionDescription attribute to RPC methods

### PR DESCRIPTION
**Pull request by quantumagi**

### CODE REVIEW

**Comment by bokobza** [comment]
1. How do you know whether an action like Stop is an RPC method (so that the json returned only contains RPC methods)?
2. the json resulting from this would look like the following:

```
[  
  [
    "stop ",
    "\"Stops the full node.\"",
  ],
  [
```
I think it can be improved to look like this:
```
[
  {
    command: "stop ",
    description: "Stops the full node."
  },
  {
     command: "getrawtransaction <txid> [<verbose>]",
```
so basically 

- adding name for the fields
- list of objects rather than array of arrays ([[]])
- remove the escaped "" in the description

**Comment by quantumagi** [comment]
1. All methods decorated with "[ActionName]" that appear on controllers of base or feature assembles are available for execution via RPC. See "RouteAsync" method of "RPCRouteHandler.cs" and "UseRpc" of "Extensions.cs". The "listmethods" method respects that fact when listing available RPC methods.
2. Done.

**Comment by quantumagi** [comment]
Added RpcCommandModel class.

**Comment by bokobza** [comment]
great stuff, thank you!

**Pull request merged**
