### PR TITLE
[Cleanup] Remove and sort usings throughout the solution

### PR DESCRIPTION
**Pull request by fassadlr**

### CODE REVIEW

**Comment by bokobza** [comment]
Thanks for doing this @fassadlr  :-)
I've checked the files and nothing looks out of order. However, a few tests are failing during the build.
Can you please have a look at that?
Cheers :-)

**Comment by bokobza** [comment]
Also it's probably time to sync your branches there so you don't have all these commits showing up lol

**Comment by fassadlr** [comment]
Hi @bokobza, I think something has gone wrong with a previous merge to my master. I'm going to re-clone and redo this properly 👍

**Comment by bokobza** [comment]
Cool, thanks mate.

**Pull request closed without merging**
