### PR TITLE
Benchmark project (with example)

### PR DESCRIPTION
**Pull request by MithrilMan**
Added a benchmark project that uses BenchmarkDotNet to perform pretty cool benchmarking.
I've created an example where I tested different implementation of DBreeze fetch of data

to run a benchmark go to the folder of benchmark project and run
`dotnet run -c Release`
then you can pick the benchmark to run (with this PR just write `0` and return)
It takes some minute to generate the output, that you can see in console or in `src\Stratis.Benchmark\BenchmarkDotNet.Artifacts\results`

BenchmarkDotNet is a powerful tool, with lot of stuffs to discover
website: https://benchmarkdotnet.org
github repo: https://github.com/dotnet/BenchmarkDotNet

### CODE REVIEW

**Comment by codingupastorm** [comment]
Thoughts on where we can put this that doesn't add to the dev solution? 

I'm thinking either:
- A second solution within this repo that references the same projects and has the benchmark project too
- A separate repo with FN submoduled

**Comment by MithrilMan** [comment]
Usually benchmarks are in the core solution, because they may benchmark internal components, but I'm open on the subject

**Comment by dangershony** [comment]
We already have 62 projects in the solution, which is quite a lot.
A second solution is not a bad idea IMO.

**Comment by MithrilMan** [comment]
The problem I see is the same that caused the decision to import the sidechain code in the solution : benchmarking can be seen as a way to chose which implementation works better in a specific scenario, and usually you are doing it against current codebase (so you can't rely on nuget packages)

**Comment by MithrilMan** [comment]
some considerations about loading time, and tips to improve:
https://sturla.io/load-and-build-solution-faster/

**Comment by codingupastorm** [comment]
In both of my suggestions above we can test internal items against the exact current code. 

I agree nuget isn't a good option, and it's not being suggested.

**Comment by codingupastorm** [comment]
Hmm looking at what big .net repositories do...

Corefx and xamarin both benchmark inside the standard test projects (though their solutions structure is fundamentally different, they're not 1 giant solution).

**Comment by MithrilMan** [comment]
Talking about tests, why not merge lot of tests in fewer projects and have folders to separate them logically?

**Pull request merged**
