### PR TITLE
Revert "Remove hex from spending details in the multi sig wallet"

### PR DESCRIPTION
**Pull request by zeptin**
We may need to rethink this, the CCTS looks for withdrawal transactions often, and this includes unconfirmed transactions within the wallet. I overlooked that in my review, so this causes exceptions stating that the withdrawal transactions can't be found. Unless unconfirmed wallet transactions can be skipped in the `ValidateCrossChainTransfers` check, which I don't believe is advisable, we will have to revert this for now. @quantumagi do you have any thoughts on this?

Also, note that there are two places in the wallet manager that save the hex into the wallet, of which only the latter one was being suppressed:
`AddTransactionToWallet`
`BuildSpendingDetails`

### CODE REVIEW

**Comment by codingupastorm** [comment]
hey @zeptin @fassadlr @quantumagi 

Some thoughts:
- We shouldn't call into the blockstore from the FWM. The FWM is always locked when used, but the blockstore could have reorged in a different thread. That error is going to be hit commonly when these components are out of sync.
- The underlying problem is "the federation wallets get too big", right? Removing the hex from SpendingDetails may not be the right answer, only delaying the issue. Instead, how about removing spent transactions from the wallet more than MaxReorg old? This could fix the problem long-term and will have performance benefits too.

(Note for a more user-friendly experience for viewing the wallet we may want to make the rule more like `once there are more than 100 transactions in the wallet remove any past the maxreorg`)

I support this PR and keeping the SpendingDetails in the wallet

**Comment by quantumagi** [comment]
Happy with this PR. It's probably more important to add indexing than to reduce the size of the wallet file, although some reductions should be possible as @codingupastorm is pointing out.

**Comment by codingupastorm** [comment]
Also if we can still bring in the changes around RecordLatestMatureDepositResult and other helpful things I think that would be good.

**Comment by fassadlr** [comment]
> * The underlying problem is "the federation wallets get too big", right? Removing the hex from SpendingDetails may not be the right answer, only delaying the issue. Instead, how about removing spent transactions from the wallet more than MaxReorg old? This could fix the problem long-term and will have performance benefits too.

I'm in favor of this @codingupastorm!

Also, yeah let's keep the result class for recording the mature deposits.

My thoughts are lets merge this, reverting the change and reintroduce the result class?

**Comment by fassadlr** [comment]
I see now that we merge conflicts. I would actually suggest that we then perhaps "revert" the changes in a PR and not a commit revert.

**Pull request closed without merging**
