### PR TITLE
appveyor build status

### PR DESCRIPTION
**Pull request by detroitpro**
Thought you might want this. 

Appveyor is free for OSS projects so you can create an account, connect to the main repo and update the shield (the image that shows if the build is passing) to be a Stratis owned Appveyor account.

### CODE REVIEW

**Comment by dangershony** [comment]
Thanks a lot let do that indeed, I guess you picked the unitest project as running integration on Appveyor is not a good idea
@Neurosploit

**Comment by Neurosploit** [comment]
I think the integration tests should also be able to run if we download the bitcoin core dependency to the right location before we start running the tests. See https://www.appveyor.com/docs/how-to/download-file/. Should be a matter of trying out. We might not want them to run every build because that would be slow but maybe with a nightly/weekly/release build.

**Comment by detroitpro** [comment]
Not yet knowing enough about the integration tests; I didn't know if they would be safe to run on there. 

Having a nightly for the integration seems like a good idea and, of course, the reason you want to follow the testing pyramid. https://martinfowler.com/bliki/TestPyramid.html

**Comment by dangershony** [comment]
@detroitpro shall I create an Appveyor stratis id or are you fine we use yours for now?

**Comment by detroitpro** [comment]
Using mine is fine but I don't have the head of master when you merge a PR.

**Comment by dangershony** [comment]
Ah right ofcourse it looks in you fork for commits.
I created an account on this repo and will change it after the commit.

**Comment by bokobza** [comment]
Hi there,
sorry I seem to have completely missed this thread but I basically did the exact same thing :grimacing:
I've added an appveyor file that builds. tests and pack nuget packages (for the release build).
I also added a badge and a link to the nuget packages in the README file.
Please feel free to have a look at my latest commit and suggest improvements.
I will add notifications at some point as well.

**Comment by detroitpro** [comment]
I think everything is covered in the other PR. Feel free to close this.

**Comment by bokobza** [comment]
Lovely, thanks @detroitpro

**Pull request closed without merging**
