### PR TITLE
Reflection extensions

### PR DESCRIPTION
**Pull request by noescape00**
Added 2 more reflection extensions

### CODE REVIEW

**Comment by dangershony** [comment]
@noescape00 there are actually calls to not use reflection anymore in tests, we are reconsidering this approach.

**Comment by noescape00** [comment]
@dangershony ok. So in case we decide to remove reflection and use internals we also should remove reflection helpers and rewrite tests that already use reflection. 
I don't mind if we use reflection or internals- both approaches are ugly, one makes the tests uglier, another makes the production code.

@Aprogiena @fenix2222 @thefazzer

Let's discuss it here.

**Comment by Aprogiena** [comment]
I am quite tired. Looks like we do something, then someone suggests that it is not the way to do, so we agree on doing something else, then we stick to it and do it like that, and then someone new comes to the code and says that how we agreed on doing things is not good and we get stuck again.

So I don't care what you choose, just choose something and make it clear that it will not change in years so that we can rely on that.

**Comment by dangershony** [comment]
I will let @fenix2222 comment on this but in the mean time lets push.

**Pull request merged**
