### PR TITLE
Fix incorrect logic for whitebind flag

### PR DESCRIPTION
**Pull request by quantumagi**
See BUG 2968.

https://dev.azure.com/Stratisplatformuk/StratisBitcoinFullNode/_workitems/edit/2968

### CODE REVIEW

**Comment by quantumagi** [comment]
@maciejzaleski , please review when you have a free moment.

**Comment by quantumagi** [comment]
@maciejzaleski , at the point where we whitebind `100.64.1.1:16178` the `CanBeMappedTo` would return `true` due to the match to `0.0.0.0:16178` so that the bind address will not be added.

**Comment by maciejzaleski** [comment]
**Issue 1**
**Local interfaces**: `192.168.1.1`, `100.64.1.1`, `127.0.0.1`
**Bind interfaces**: `0.0.0.0`
**Whitebind**: `100.64.1.1`
**Expectation**: We want to whitebind peers connecting to 100.64.1.1. Peers connecting via `100.64.1.1` or `127.0.0.1` should not be whitbinded
**Result**: All interfaces will be whitebinded

```public static bool CanBeMappedTo(this IPEndPoint whiteBindEndpoint, List<IPEndPoint> networkEndpoints, out IPEndPoint localEndpoint)```

- whiteBindEndpoint=`100.64.1.1`
- anyIP=false
- networkEndpoints=`0.0.0.0`
- CanBeMappedTo returns `true` 

**Issue 2**
In CanBeMappedTo you only compare the IP and not the port in the second conditional statement

**Issue 3**
I suspect that the current logic only allow to whitebind incoming connections. I think we should be able to whitebind outgoing connections as well if they use the whitebinded local interface

**Comment by quantumagi** [comment]
I assume you meant: `
**Expectation**: We want to whitebind peers connecting to 100.64.1.1. Peers connecting via `192.168.1.1` or `127.0.0.1` should not be whitebinded`.

Also can you confirm that the following two legacy test cases need to change as follows (`Assert.False` instead of `Assert.True`):

```
            // IPV4: 127.0.0.1:16178 != 0.0.0.0:16178 (both are considered local endpoints)
            endpointA = new IPEndPoint(IPAddress.Parse("127.0.0.1"), 16178);
            endpointB = new IPEndPoint(IPAddress.Parse("0.0.0.0"), 16178);
            networkEndpoints = new List<IPEndPoint>() { endpointB};
            connectionManagerSettings.Port = 16178;
            Assert.False(endpointA.CanBeMappedTo(networkEndpoints, out endpointOut));

            // IPV6: [::1]:16178 != [::]:16178
            endpointA = new IPEndPoint(IPAddress.Parse("[::1]"), 16178);
            endpointB = new IPEndPoint(IPAddress.Parse("[::]"), 16178);
            networkEndpoints = new List<IPEndPoint>() { endpointB };
            connectionManagerSettings.Port = 16178;
            Assert.False(endpointA.CanBeMappedTo(networkEndpoints, out endpointOut));
```

**Comment by quantumagi** [comment]
Not sure if this legacy code is performing a valid test:

```
            if (this.Bind.Count == 0)
            {
                this.Bind.Add(new NodeServerEndpoint(new IPEndPoint(IPAddress.Parse("0.0.0.0"), this.Port), false));
            }
            else
            {
                var ports = this.Bind.Select(l => l.Endpoint.Port).ToList();

                if (ports.Count != ports.Distinct().Count())
                {
                    throw new ConfigurationException("Invalid attempt to bind the same port twice");
                }
            }
```

The `Bind` array could contain both `{ EndPoint: 0.0.0.0:16178, WhiteBind: false }` and `{ EndPoint: 100.64.1.1:16178, WhiteBind: true }` which would cause the above code to raise an error.

**Comment by codingupastorm** [comment]
I'm not the right person to approve this - I don't know this area well enough. 

But I can say that the code's current behaviour is strange. This happens in the default case in ConnectionManagerSettings:

```
            if (this.Bind.Count == 0)
            {
                this.Bind.Add(new NodeServerEndpoint(new IPEndPoint(IPAddress.Parse("0.0.0.0"), this.Port), false));
            }```

Which means that all incoming connections on the default port will be allowed here in NetworkPeerServer:228

```
            var clientLocalEndPoint = tcpClient.Client.LocalEndPoint as IPEndPoint;

            bool endpointCanBeWhiteListed = clientLocalEndPoint.CanBeMappedTo(this.connectionManagerSettings.Bind.Select(x => x.Endpoint).ToList(), out IPEndPoint endpoint);

            if ((endpoint != null) && endpointCanBeWhiteListed)
            {
                this.logger.LogTrace("(-)[ENDPOINT_WHITELISTED_ALLOW_CONNECTION]:true");
                return true;
            }
```

@dangershony @thefazzer can you guys look at this?

**Comment by dangershony** [comment]
@codingupastorm that's correct if no bind is specified we use default port, however if server=0 we don't even open the tcp receive port for incoming connections  
ConnectionManager.cs line 144
```
            if (this.ConnectionSettings.Listen)
                this.StartNodeServer();
```

**Comment by codingupastorm** [comment]
@dangershony yes, you are correct. But running the node without any params will default to listen=true.

And then other nodes will (theoretically) be able to connect during IBD.

**Comment by dangershony** [comment]
@codingupastorm to prevent IBD we have this code


in NetworkPeerServer.AcceptClientsAsync()

```
                    if (!this.AllowClientConnection(tcpClient))
                    {
                        this.logger.LogTrace("Connection from client '{0}' was rejected and will be closed.", tcpClient.Client.RemoteEndPoint);
                        tcpClient.Close();
                        continue;
                    }
```

Internally
```
            if (!this.initialBlockDownloadState.IsInitialBlockDownload())
            {
                this.logger.LogTrace("(-)[IBD_COMPLETE_ALLOW_CONNECTION]:true");
                return true;
            }
```

**Comment by maciejzaleski** [comment]
Retest failed, Attempt to whitebind localhost will disable peer server on external interface.

With the following settings the node will not be able to accept external connections (neither from the same LAN nor from Internet).
```
port=16178
whitebind=127.0.0.1:16178
```

**Comment by quantumagi** [comment]
The following code snippet from Bitcoin suggests that we are matching the Bitcoin behavior:
```

bool CConnman::InitBinds(const std::vector<CService>& binds, const std::vector<CService>& whiteBinds) {
    bool fBound = false;
    for (const auto& addrBind : binds) {
        fBound |= Bind(addrBind, (BF_EXPLICIT | BF_REPORT_ERROR));
    }
    for (const auto& addrBind : whiteBinds) {
        fBound |= Bind(addrBind, (BF_EXPLICIT | BF_REPORT_ERROR | BF_WHITELIST));
    }
    if (binds.empty() && whiteBinds.empty()) {
        struct in_addr inaddr_any;
        inaddr_any.s_addr = INADDR_ANY;
        struct in6_addr inaddr6_any = IN6ADDR_ANY_INIT;
        fBound |= Bind(CService(inaddr6_any, GetListenPort()), BF_NONE);
        fBound |= Bind(CService(inaddr_any, GetListenPort()), !fBound ? BF_REPORT_ERROR : BF_NONE);
    }
    return fBound;
}
```

**Pull request merged**
