### PR TITLE
[ChainState] Pass DateTimeProvider via dependency injection to constructor

### LINKED ISSUE #904: [ChainState] use normal DI, do not pull DTP from FullNode service
Such non-standard DI gives us trouble when we have testing environment with not fully initialized FullNode.

### PR DESCRIPTION
**Pull request by fassadlr**
This fixes #904 .

### CODE REVIEW

**Comment by Aprogiena** [comment]
actually, could we remove the full node dependency completely and replace it with IBlockDownloadState dependency?

**Comment by fassadlr** [comment]
> actually, could we remove the full node dependency completely and replace it with IBlockDownloadState dependency?

Even better!

PS do you know what IBlockDownloadState does? There's no documentation on that interface anywhere in the code :(

**Comment by Aprogiena** [comment]
its only purpose is to provide IBD check
so it should be trivial to mock in tests

**Comment by fassadlr** [comment]
@Aprogiena OK wow this send me down circular dependency hell!

In BaseFeature we configure:

`services.AddSingleton<ChainState>();`

In ConsensusFeature we configure IBlockDownloadState as:

```
services.AddSingleton<ConsensusManager>()
    .AddSingleton<IBlockDownloadState, ConsensusManager>()
    .AddSingleton<INetworkDifficulty, ConsensusManager>();
```

ConsensusManager takes in ChainState:

```
public ConsensusManager(ICheckpoints checkpoints, ConsensusLoop consensusLoop = null, IDateTimeProvider dateTimeProvider = null, NodeSettings nodeSettings = null, Network network = null,
            PowConsensusValidator consensusValidator = null, ChainState chainState = null)
```

If we change ChainState to take in IBlockDownloadState:

```
public ChainState(IBlockDownloadState blockDownloadState, IDateTimeProvider dateTimeProvider, IInvalidBlockHashStore invalidBlockHashStore)
{
```

Boom! We have a circular dependency! Urgh this is not good. Something seems off here.

I dont think its good design to ask services for ConsensusManager via IBlockDownloadState ??

**Comment by fassadlr** [comment]
@Aprogiena either we revisit the design here in another PR, or we just do the quick fix for now and inject FullNode.

**Comment by Aprogiena** [comment]
The situation might not be as bad as it seems.
How about removing ChainState from ConsensusManager?
it seems very possible

but maybe @dangershony would know if there is not some problem with that?

**Comment by Aprogiena** [comment]
I think the only problem will be when there is no consensus, then we will need to implement that interface to return false, but that seems trivial as well

**Comment by fassadlr** [comment]
ConsensusManager only use ChainState in getting the ConsensusTip here:
```
public Target GetNetworkDifficulty()
{
    if ((this.ConsensusValidator?.ConsensusParams != null) && (this.ChainState?.ConsensusTip != null))
        return this.ChainState?.ConsensusTip?.GetWorkRequired(this.ConsensusValidator.ConsensusParams);
    else
        return null;
}
```

Why dont we just pass ChainState to GetNetworkDifficulty?

**Comment by Aprogiena** [comment]
why don't we use this.ConsensusTip instead of this.ChainState.ConsensusTip?

**Comment by fassadlr** [comment]
This is crappy design... the dependency graph just keeps going deeper. Its not right to configure a DI container for something that is essentially just a polymorphic property. This is wrong IMO:

```
services.AddSingleton<ConsensusManager>()
            .AddSingleton<IBlockDownloadState, ConsensusManager>()
            .AddSingleton<INetworkDifficulty, ConsensusManager>();
```

What we are saying here is that if we ask Services for IBlockDownloadState, give us an instance of ConsensusManager?! We are only interested in IsInitialBlockDownload.

IMO ChainState should NOT be constructed with IBlockDownloadState but rather, we should just pass IBlockDownloadState to IsInitialBlockDownload() method. That way we remove the dependency.

**Comment by fassadlr** [comment]
Very much an oversimplified idea, but I think the direction is better ;)

**Comment by fassadlr** [comment]
The idea (and what the intent was) of the IBlockDownloadState interface is an excellent one 👍  Its just then we need to properly implement a provider so that we can get rid of these dependencies ;)

**Comment by Aprogiena** [comment]
i don't know what you mean by passing IBlockDownloadState to IsInitialBlockDownload
to me it seems that the true provider of IBD is ConsensusLoop
and that ChainState is not needed inside ConsensusManager
it seems like we can get rid of the circular dependency easily
but if you think further improvements are needed in the design, feel free to try that, but i don't understand what you mean

**Comment by fassadlr** [comment]
@Aprogiena @noescape00 I'm closing this PR so that we can continue discussions in #921 and subsequently do a PR from that issue.

**Pull request closed without merging**
