### PR TITLE
[ACTIVATION] Redundant files removal

### PR DESCRIPTION
**Pull request by noescape00**
#1877

### CODE REVIEW

**Comment by noescape00** [comment]
they are not used anywhere. 
also half of them belong to component which we disconnected for good (block store cache)

**Comment by bokobza** [comment]
Every dev that wants to remove code gets a special place in my heart.

**Comment by Aprogiena** [comment]
agree with most, but not sure about block repository one

**Comment by noescape00** [comment]
>agree with most, but not sure about block repository one

1) When was last time anyone looked at those performance metrics? 
2) We have logs to investigate performance issues
3) DBreeze is never a bottleneck
4) This performance counter has interface which is overkill: `AddCacheHitCount(1);` and other methods always accept integer but never any value except for 1 is passed
5) There is `public virtual BlockStoreCachePerformanceCounter BlockStoreCachePerformanceCounterFactory()` do we really need to have it? Do we expect some component to inherit from block store and override performance counter?
6) AddRepositoryMissCount - this shouldn't even exist. If component asks for a block which is not on best chain from the repository then this component has a bug or there was a reorg just recently

**Comment by Aprogiena** [comment]
LOL, seven reasons, okay I guess then

**Comment by bokobza** [comment]
Alt Text

**Pull request merged**
