### PR TITLE
[FN] Signalr feature

### PR DESCRIPTION
**Pull request by fenix2222**
A new opt-in feature to add signal r notifications. Idea is to be able to propagate Full Node internal signals to connected UI clients.

### CODE REVIEW

**Comment by fenix2222** [comment]
@MithrilMan When would you be able to check this one?

**Comment by MithrilMan** [comment]
will review soon, not today, probably tomorrow

**Comment by MithrilMan** [comment]
PR delayed but still on radar, do not close this PR thanks.

**Comment by fassadlr** [comment]
Closing as this merge with #3901

**Pull request closed without merging**
