### PR TITLE
[WIP] Implement transaction broadcasting and propagation 3 ways

### PR DESCRIPTION
**Pull request by nopara73**
Superseeds: https://github.com/stratisproject/StratisBitcoinFullNode/pull/470

ToDo:  
@dev0tion We need to resolve this issue before it gets merged: https://github.com/stratisproject/Breeze/issues/207  
@bokobza Please sort out the tests. Because from now on we don't get false positive results testing without real network is impossible. In `WalletControllerTests` `SendTransactionFailedReturnsBadRequest` and `SendTransactionWithExceptionReturnsBadRequest` are failing.  
Furthermore please remove the WalletManager's sendtransaction, because the wallet is not the one who broadcasts and propagates the transaction. At least not anymore. I don't remove it because, many more tests would fail.

### CODE REVIEW

**Comment by dangershony** [comment]
Ah jesus this has a dependency on the awaiter extension, it will be very hard to review.

**Comment by nopara73** [comment]
@dangershony I reviewed it, no worry:)  
Jokes aside, we talked about this before and you said it'll be fine like this. Not sure why you're surprised.

**Comment by dangershony** [comment]
Generally we need to separate such PR so one does not depend on the other.

**Comment by dangershony** [comment]
Is there anyway this can not be a dependency of #484

**Pull request closed without merging**
