### PR TITLE
Should stake store flush be inside the lock?

### PR DESCRIPTION
**Pull request by dangershony**

### CODE REVIEW

**Comment by Aprogiena** [comment]
Quite nontrivial change in terms of possible impact, yet no rationale provided

**Comment by dangershony** [comment]
Will it not prevent flushing out of sync from coinview?

**Comment by Aprogiena** [comment]
No, if there is power failure, locking does not help

If you have different scenario in mind, you need to describe it

**Comment by dangershony** [comment]
ok this is solved and was never a problem

**Pull request closed without merging**
