### PR TITLE
Fix the path for logging when -datadir and working folder specified

### PR DESCRIPTION
**Pull request by sondreb**
- Included unit test verifies the implemented logic, but not the actual implementation. #1307

### CODE REVIEW

**Comment by Aprogiena** [comment]
Please see my comments in #1307

**Comment by bokobza** [comment]
From what I see when running the node, the Datafolder paths are always rooted so I'm not sure what this fixes.
If this is to support the case where a non-rooted DataFolder is passed, I'm not sure this is necessary.

Also the tests seems to be testing the system.IO.Path class rather than any of our classes. Is that intentional?

**Comment by bokobza** [comment]
I stand corrected, they're not if you specify the datadir in the command line.
If there's no root in the DataFolder paths, the current directory will be used, so the questions remain.

**Comment by bokobza** [comment]
@sondreb @Aprogiena  I found the issue.
In NodeSettings.cs if datadir is not null, we create a folder for it, but the DataDir property itself stays root-less, so all the paths in DataFolder are without a root.

Have a look:
```
// Setting the data directory.
if (this.DataDir == null)
{
	this.DataDir = this.CreateDefaultDataDirectories(Path.Combine("StratisNode", this.Network.RootFolderName), this.Network);
}
else
{
	// Create the data directories if they don't exist.
	string directoryPath = Path.Combine(this.DataDir, this.Network.RootFolderName, this.Network.Name);
	---> Directory.CreateDirectory(directoryPath);
    ---> this.DataDir = directoryPath;
	this.Logger.LogDebug("Data directory initialized with path {0}.", directoryPath);
}
```

The fix is to replace
```
Directory.CreateDirectory(directoryPath);
this.DataDir = directoryPath;
```
by 
`this.DataDir = Directory.CreateDirectory(directoryPath).FullName;`

and it should be ok.
@sondreb I'll let you do it.

**Comment by Aprogiena** [comment]
So as we merged the other PR fixing this, we can probably close this, right?

**Comment by bokobza** [comment]
yep.

**Pull request closed without merging**
