### PR TITLE
Async7

### PR DESCRIPTION
**Pull request by nopara73**

### CODE REVIEW

**Comment by Aprogiena** [comment]
in release mode, appveyor reports inability to compile, we probably need to appveyor configuration before merging this

**Comment by nopara73** [comment]
@Aprogiena Maybe it'll be the C# 7.1 syntax. (async main) Will look at it on Monday.

**Comment by Aprogiena** [comment]
yes it is that

**Comment by bokobza** [comment]
```
 <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
      <NoWarn>1701;1702;1705;IDE0008;</NoWarn>		
    <LangVersion>latest</LangVersion>
    </PropertyGroup>	
```

The LangVersion here is only for Debug|AnyCPU configuration so you need to add the equivalent for the Release config.

**Comment by nopara73** [comment]
Fixed and replaced by: https://github.com/stratisproject/StratisBitcoinFullNode/pull/588

**Pull request closed without merging**
