### PR TITLE
Stratis DB class for smoothing transition to new DB store

### PR DESCRIPTION
**Pull request by quantumagi**
This concept PR introduces the `IStratisDB` interface and a interim `StratisDB` class as per https://github.com/stratisproject/StratisBitcoinFullNode/issues/3340.

### CODE REVIEW

**Comment by noescape00** [comment]
Please wait with this. We are not sure if there will be a new db or that new db will be transaction based

**Comment by quantumagi** [comment]
@noescape00, please add your comments to the issue and we can discuss there.

**Comment by noescape00** [comment]
The problem here is that we don't really have many alternatives to replace dbreeze with. Best one is leveldb which doesn't have concept of transactions.

**Comment by quantumagi** [comment]
This is an interesting read: https://stackoverflow.com/questions/9022691/what-constitutes-a-transaction-layer-when-talking-about-database-systems. In limited scenarios ACID properties can be implemented via some layer of abstraction as made possible by the suggested interfaces. If code changes are going to be required then LevelDB becomes a less attractive option.

**Comment by codingupastorm** [comment]
I like the idea behind this @quantumagi !!

My main feedback would be that I think we should try and only include code like this when it's being used, i.e. the rest of the solution starts consuming `IStratisDB`.

Others raise fair points as well about the features of other databases - maybe we need a more general interface.

**Comment by quantumagi** [comment]
The interface as defined currently fully supports the BlockRepository feature. I have not checked the rest yet.

**Comment by MithrilMan** [comment]
I vote for abstracting DBreeze with a generic interface (this is what I was talking about during the db call @dangershony )
The only thing I'd say is about the name, instead of refers to Database (DB) I'd use the Storage naming

**Comment by dangershony** [comment]
This is too tightly coupled to dbreeze.
We should create a wrapper Commit component that can be passed around and the top level component (in this case CahedCoinview) will call commit, this component can be then passed down to the other stores (PosStore for example)

**Comment by quantumagi** [comment]
Which part of this is too tightly coupled to DBreeze?:

```
    public enum StratisDBTransactionMode
    {
        Read,
        ReadWrite
    }

    public interface IStratisDBTransaction : IDisposable
    {
        void Insert<TKey, TObject>(string tableName, TKey key, TObject obj);
        void InsertMultiple<TKey, TObject>(string tableName, (TKey, TObject)[] objects);
        void InsertDictionary<TKey, TObject>(string tableName, Dictionary<TKey, TObject> objects);
        bool Select<TKey, TObject>(string tableName, TKey key, out TObject obj);
        List<TObject> SelectMultiple<TKey, TObject>(string tableName, TKey[] keys);
        Dictionary<TKey, TObject> SelectDictionary<TKey, TObject>(string tableName);
        IEnumerable<(TKey, TObject)> SelectForward<TKey, TObject>(string tableName);
        void RemoveKey<TKey, TObject>(string tableName, TKey key, TObject obj);
        void RemoveAllKeys(string tableName);
        bool Exists<TKey>(string tableName, TKey key);
        bool[] ExistsMultiple<TKey>(string tableName, TKey[] keys);
        void Commit();
        void Rollback();
        string ToString();
    }
```

**Comment by dangershony** [comment]
Ok I see the intention of this PR, to create a db library abstraction layer.
I think we are trying to make the too many layers of abstraction here, as long as the DBreeze engine is contained to the repo (and the repo's interface does not leak any dbreeze types in the signature) the entire repo can be replaced to support a different db.
 So we have an 
`IBlockReposotory` and two implementation `DBreezeBlockRepository` and say `LiteDBBlockReposiroty`

A Quick look in the code I see that DBreeze types are not leaked outside of repos so we already have abstraction and this PR is not needed (unless we want to make cached coinview support a muilty component commit for example flush StakeStore then DBreezeCoinView then commit both in one trx)

**Comment by fassadlr** [comment]
Closing this for now. If the need arises for us to have an abstraction we can revisit this PR.

**Pull request closed without merging**
