### PR TITLE
Store only IPv6 or IPv4 in embedded format

### PR DESCRIPTION
**Pull request by dangershony**
Fix: #1153 

This is one for @345paul and @fassadlr

### CODE REVIEW

**Comment by 345paul** [comment]
Looks ok.  I think the peer file was ok, but it doesn't hurt to ensure it is converted on load.  The AddPeer method looks fine.

**Comment by dangershony** [comment]
I did review all places but your suggestion (in private) to do it in the Create method is actually better updating PR

**Comment by 345paul** [comment]
Looks good.  I see you've put a change in to make the ConcurrentDictionary private and expose a simple List generated from the dictionary on access of the property.  I assume that you wanted a simpler list exposed for other reasons, as I'm not sure this is relevant to the issue being fixed?

**Comment by dangershony** [comment]
Yes it came up in another PR so I just fixed it here, but this is the right place as it will prevent any other components from adding to the ConcurrentDictionary none embedded ip addresses

**Comment by dangershony** [comment]
Also the reason for using the `this.peers.Select(item => item.Value).ToList()` can be found here https://arbel.net/2013/02/03/best-practices-for-using-concurrentdictionary/

**Pull request merged**
