### PR TITLE
Fix failing CreateCoinBase and CreateNewBlock test cases

### PR DESCRIPTION
**Pull request by quantumagi**
This PR fixes the following error:

`Message: System.ArgumentOutOfRangeException : The UTC time represented when the offset is applied must be between year 0 and 10,000.
Parameter name: offset`

The error occurs in the following test cases:

- CreateCoinbase_CreatesCoinbaseTemplateTransaction_AddsToBlockTemplate
- CreateNewBlock_WithScript_DoesNotValidateTemplateUsingRuleContext
- CreateNewBlock_WithScript_ReturnsBlockTemplate
- CreateNewBlock_WithScript_ValidatesTemplateUsingRuleContext

### CODE REVIEW

**Comment by Aprogiena** [comment]
With the latest master, all the mentioned tests pass for me. Under which conditions are those tests supposed to fail?

**Comment by Aprogiena** [comment]
@quantumagi I agree that using the one method instead of 2 is better, I just do not see why it fails or when it fails, because for me those tests simply pass. So I'm just interested to understand the problem, but I have no problem with this change in code.

**Comment by quantumagi** [comment]
I've done a cross-check by reverting the changes against the latest code from master. It still fails with the two calls. Unfortunately I can't step into those methods for some reason.

**Comment by fassadlr** [comment]
@Aprogiena will approve this one when the PR is done then? Cheers 👍

**Comment by quantumagi** [comment]
I think we can handle this as a simple refactor as the remaining issue seems to be at my end.

**Comment by Aprogiena** [comment]
I'm not running tests, so I now just comment on issues and pull request, so I cannot really approve, but it looks fine to me

**Comment by fassadlr** [comment]
@Aprogiena 👍 

@quantumagi sorry I misunderstand, will now recreate the PR? I see Travis is still failing.

**Comment by quantumagi** [comment]
@fassadlr, those are unrelated errors which will be fixed by https://github.com/stratisproject/StratisBitcoinFullNode/pull/1332.

**Pull request merged**
