### PR TITLE
Duplicate log messages

### PR DESCRIPTION
**Pull request by thefazzer**
https://stratisplatformuk.visualstudio.com/StratisBitcoinFullNode/_workitems/edit/3003

_...inefficient log messages where we log similar message on two different log levels.
Since the log messages logged on Error level are also included on Trace level there is no reason to log them twice._

@fazz: Fix replaces any two sequential log messages at different levels of granularity with one combined message output at the coarsest (lowest) level.

Preferred: @maciejzaleski

### CODE REVIEW

**Comment by thefazzer** [comment]
> They are not duplicated. One is a normal log and 2nd is an exit log.
> This PR violates logging style. To apply such changes logging style should be changed first.

Thx @noescape00 - I understand your first point.  Can you pls clarify or make a suggestion as to how we could address the problem so the code follows the style guidelines.

**Comment by noescape00** [comment]
`make a suggestion as to how we could address the problem so the code follows the style guidelines.`

It follows codestyle right now so I don't see the need to change it.

**Comment by dangershony** [comment]
Many of the changes made here are not duplicated log messages.
I don't consider this to be a duplicate:
```
this.logger.LogError("Exception occurred: {0}", ex.ToString());	                this.logger.LogError("Exception occurred: {0}" + "\r\n" + "(-)[EXCEPTION]", ex.ToString());
                this.logger.LogTrace("(-)[EXCEPTION]");
```

**Comment by noescape00** [comment]
This PR violates logging style. To apply such changes logging style should be changed first. Reopen when logging style is changed.

**Pull request closed without merging**
