### PR TITLE
Upgrade to .NETCore 2.2

### PR DESCRIPTION
**Pull request by bokobza**
Ran unit and integration tests without problem. 
Also running the 4 networks, so far without any issue (> 100K blocks in each).

Please wait for results from the build.

### CODE REVIEW

**Comment by bokobza** [comment]
@monsieurleberre you're right look
image


image

**Comment by bokobza** [comment]
I've followed the instructions here https://edi.wang/post/2018/12/13/build-dotnet-core-22-projects-on-azure-devops

Let's see if it works.
Thanks @monsieurleberre .

**Comment by monsieurleberre** [comment]
I think there is something a bit tight with our build agents, we need to speak to Iain
I managed to have one building on my own azure devops ...
https://dev.azure.com/matthieu-yal/VSTS%20demos/_build/results?buildId=256

**Comment by bokobza** [comment]
I made it work the other day, have a look at the disabled task in the Windows build.
I'm waiting for the next release to push this PR.

**Pull request closed without merging**
