### PR TITLE
Replace .Wait(), .Result, .GetAwaiter().GetResult() with await .Confi…

### PR DESCRIPTION
**Pull request by nopara73**
…gureAwait(false) in Test projects

As a starting point of resolving the issue: https://github.com/stratisproject/StratisBitcoinFullNode/issues/565

### CODE REVIEW

**Comment by dangershony** [comment]
@Neurosploit can you help review this as well?

**Comment by dangershony** [comment]
@nopara73 we normally try to work with smaller commits so its easier to review.

**Comment by Neurosploit** [comment]
Can you first clarify why configureawait(false) is needed at all? See http://blog.stephencleary.com/2017/03/aspnetcore-synchronization-context.html

**Comment by dangershony** [comment]
Ha they dropped the `AspNetSynchronizationContext` wowoo so the aspnet core context is now multi threaded by default.

We can remove that in tests but in libraries (the fullnode) we probably keep it.

**Comment by nopara73** [comment]
@Neurosploit What do you propose?  
ConfigureAwait(false) in Stratis.Bitcoin, NStratis and Features projects  
and not ConfigureAwait(false) in Tests, Api, Cli and Daemon projects?  

@dangershony  What do you think?

**Comment by Neurosploit** [comment]
Sounds good @nopara73.

**Pull request closed without merging**
