### PR TITLE
Move from xUnit to MsTest

### PR DESCRIPTION
**Pull request by Neurosploit**
xUnit was just doing my head in. Visual studio support is just not working as it should in combination with test discovery.
I've attempted to move the test projects from xUnit to MsTest refactoring all tests to the new framework. 
I hope with this we can speed things up a bit. The changes aren't world changing but we should run into less issues by using their own framework.
I've dropped the program.cs files in the test projects they are no longer needed anymore.
I've also updated the test guidelines documentation.

Please rebuild the solution and run the tests to see they are passing. I've only tested it on windows so far and for me everything was green.
To run tests outside visual studio:
dotnet test in a project folder or dotnet test {path to csproj}.

### CODE REVIEW

**Comment by bokobza** [comment]
I'll review it

**Comment by dangershony** [comment]
Ah sounds much better I was also battling xunit a lot

**Comment by bokobza** [comment]
Is the content of Stratis.Bitcoin.IntegrationTests/Program.cs not necessary anymore? @Neurosploit

**Comment by Neurosploit** [comment]
I tried running the tests without it. They passed just fine.

**Comment by bokobza** [comment]
Cool then :-)
I've run the tests on windows but WalletCanReorg fails, as was expected.
I'm going to try on Linux.

**Comment by bokobza** [comment]
there are some spurious failures on Linux
for the unit tests:
image

for the integration tests, only WalletCanReorg fails.

**Comment by bokobza** [comment]
I'm happy with the results, we can fix the linux tests later.
Thanks @Neurosploit !

**Pull request merged**
