### PR TITLE
Set Maximum Allowable Connections

### PR DESCRIPTION
**Pull request by D3m0nKingx**
In The Stratis.Bitcoin.Connection.ConnectionManager class,  change the NodesGroup's MaximumNodeConnection :

Add to DiscoveredNodeGroup.MaximumNodeConnection = 16

I've tested this with 125 connections with success, furthermore, doing so increases the list of peers in addrman.dat and improves connection performance upon restart of the node.

### CODE REVIEW

**Comment by dangershony** [comment]
Hi @D3m0nKingx I don't think it should be more then the default 8 nodes for outbound. 
This parameter is for outbound connections, if you make too many outbound connections you are leeching on the network.

See this post from Gavin
https://www.reddit.com/r/Bitcoin/comments/1scd4z/im_running_a_full_node_and_so_should_you/cdw3lrh/

**Comment by D3m0nKingx** [comment]
Well Andresen is recommending running as a full node (more than 8 connections), That was how it was determinable if a Bitcoin Node is running as a full node or not (Bitcoin's default 8 is arbitrary in my opinion, but a simple indicator if you're running as a full node). 

In regards to leeching (taking resources without giving any back) by only connecting outbound isn't recommended in general because  Nodes without their port open cannot make connections with nodes joining the network or looking for more connections, thus it's better to be setup as a Full Node that is **seeding** (have an open port listening for **incoming** connections, i.e. port 16178 for Stratis) which is what makes a full node a full node. 

Thus I see no issue with having 16 connections and maintaining an open port for other nodes to connect and keep the network aware of other available nodes.

**Comment by dangershony** [comment]
But if you hard code it to the client you force that, most nodes don't have their ports open.
If your port is open and you know what your doing then you'll most likely get more then 8 connections anyway it will just take longer.

**Comment by D3m0nKingx** [comment]
Not sure there's a negative impact in having more than 8 connections (i.e. performance, etc) ?

My understand is StratisD is set to default 8 connections, so even if it's listening for nodes it may or may not establish any incoming connections, so why not have 16 as does StratisX ?

The 125 connections I am running with, it's using minimal resources on my system (CPU: 1-50% of 1 core, RAM: 4%, NET: +/- 10kb/s). Could you explain the drawback you think this would cause? I don't see one, since today's systems and internet providers have plenty of resources and bandwidth available.

**Comment by Derrick-** [comment]
Even with only 8 outgoing connections, my long-running full bitcoin nodes have consistently more than 30 connections due to inbounds. Such inbounds will accumulate on a an extremely stable node, which is good. 

SPV nodes, most of which I speculate are short lived on the network need additional these full node connection slots.

I agree that 8 is a good number for outgoing connections, it's enough to maintain a resilient connection as nodes go up and down, but I don't think the incoming connections should be limited to 8, although some limit is probably a good idea. Should be closer to 100 than 16 though imho.

**Comment by dangershony** [comment]
So what did we decide on this? currently the outbound is restricted to 8 and inbound to 125 (bitcoin default) 
Is the Stratis default the same? 
Perhaps it will be better to change the PR to take a configurable inbount/outbound settings so its possible to do it on the node builder.

**Comment by D3m0nKingx** [comment]
From discussion in slack, As long as inbound connections are present, then current default of 8 outbound / 125 inbound is acceptable. And yes I'd agree about making it a configurable option for users to adjust accordingly to their preferences. 

So we can for the meantime keep the current settings as is. If you agree, This PR can be closed

**Comment by dangershony** [comment]
Yeah I agree, so I will close it.

**Pull request closed without merging**
