### PR TITLE
Remove stylecop

### PR DESCRIPTION
**Pull request by noescape00**
Stylecop is not configured to support our codestyle. Instead in many places it spawns a warning asking to change correct codestyle to incorrect. This behavior only slows down working on the codebase and doesn't give any benefits. 

Stylecop should be configured or removed. Please close this PR if there is a volunteer who would like to configure it. 

ps
I'd go with removing it because most of the style rules are already enforced with resharper

### CODE REVIEW

**Comment by MithrilMan** [comment]
If you create an Issue about this, I've something to add:

using Directory.Build.Props
https://docs.microsoft.com/en-us/visualstudio/msbuild/customize-your-build?view=vs-2017

Here an example about how I configured it for my Debug feature in my repo

https://github.com/MithrilMan/StratisDebugFeature/blob/master/src/Directory.Build.props

**Comment by noescape00** [comment]
@bokobza I've updated the PR to remove only Settings.StyleCop files

Now after reverting the rest of the PR I have again things like this:




Could you please configure those for entire solution or tell me how do I configure it exactly?

**Comment by bokobza** [comment]
@noescape00 Sure mate, let me have a go. I'll keep this PR open for now so that people don't have nightmares.

**Comment by noescape00** [comment]
@bokobza thanks a lot 🙂 
Add changes to this PR if you'd like, I think that would be a good idea

**Comment by MithrilMan** [comment]
I really suggest using using Directory.Build.Props for the entire solution, so no need to tweak every single project, they should just adhere to a common style (is it possible to exclude some project in that file, if needed)

**Comment by noescape00** [comment]
@dangershony @bokobza I don't mind if we try idea that @MithrilMan is proposing as long as he configures the Directory.Build.Props.

But the decision is up to you, I really don't have a strong position here.

**Comment by bokobza** [comment]
yeah I'm using it. Also look at Matt's PR where he's used custom props files: https://github.com/stratisproject/StratisBitcoinFullNode/pull/3053

**Comment by bokobza** [comment]
@noescape00 I've started on another branch as I started doing this in the tube yesterday and couldn't download your branch. 🚇

**Comment by noescape00** [comment]
@bokobza ok, great. In that case feel free to close or merge this PR.

**Comment by bokobza** [comment]
Done somewhere else.

**Pull request closed without merging**
