### PR TITLE
Return wallet file path in general-info api call

### LINKED ISSUE #883: WalletFilePath returns Null
Per conversation with @mikedennis we determined the Wallet Controller isn't filling the parameter for WalletFilePath in https://github.com/stratisproject/StratisBitcoinFullNode/blob/15d3ddcbf9a0da23ab8e5c775c893c26f269f515/src/Stratis.Bitcoin.Features.Wallet/Models/WalletGeneralInfoModel.cs#L10

Resulting in general-info api request to the node returning null:
```bash
{
  "walletFilePath": null,
  "network": "Main",
  "creationTime": "1512431701",
  "isDecrypted": true,
  "lastBlockSyncedHeight": 498757,
  "chainTip": 498757,
  "isChainSynced": true,
  "connectedNodes": 8
}
```

Possibly the Name Parameter should be the name of the Wallet?

### PR DESCRIPTION
**Pull request by mikedennis**
This fixes #883

### CODE REVIEW

**Comment by bokobza** [comment]
Hi Mike, there is already a method that does that for you.
Look at a method called `ListWalletsFiles()` in the `WalletController`.

**Comment by mikedennis** [comment]
Yes I did look at that but since I have the walletname I would have had to do some filename manipulation to find the right entry which I thought would be amount the same amount of work as adding a new method to build it from the name. What do you think?

Also since we have already have this API method is there value of having the path in the general-info call at all?

**Comment by bokobza** [comment]
The this.walletManager.GetWalletsFiles() call gives you the path and the list of names.
Just combine the path with the name you're looking for and you're done. I think the extension is included in the result.
Also, you're code will give you a path even if there is no wallet with this name present.

**Comment by mikedennis** [comment]
Yes good point. Will do- thanks!

**Comment by bokobza** [comment]
All good, just one tiny thing.

**Comment by mikedennis** [comment]
@bokobza Are you keeping me in suspense? :grin: I don't think you applied your review.

**Comment by bokobza** [comment]
Did I not? Oh right.
So I was saying that the this.walletManager.GetWalletsFiles() already has extension in the filenames.
like this:
```
{
    "walletsPath": "C:\\Users\\jerem\\AppData\\Roaming\\StratisNode\\stratis\\StratisTest",
    "walletsFiles": [
        "newwallet.wallet.json",
        "recovered2.wallet.json",
        "recoveredwallet.wallet.json"
    ]
}
```

**Comment by mikedennis** [comment]
Are you referring to this line?
```            string searchFile = Path.ChangeExtension(request.Name, this.walletManager.GetWalletFileExtension());```

I'm just using this to build a filename to lookup against walletFiles since the request only has the walletname in it.

**Comment by bokobza** [comment]
Ah yes of course!

**Pull request merged**
