### PR TITLE
Create seperate projects for Wallet, MemoryPool, Miner and BlockStore

### PR DESCRIPTION
**Pull request by quantumagi**
The main purpose of this PR is to create separate projects for 4 additional features leaving 2 remaining featured (Consensus and Notifications):

- Create separate projects for Wallet, MemoryPool, Miner and BlockStore (initial split) and update references
- Update "appveryor.yml" and "build.sh" to include new test projects
- Remove most feature dependencies from Stratis.Bitcoin.Tests (FullNodeBuilderTests)
- Move tests to test projects and update namespaces
- Fix data folder of BaseRPCControllerTest to avoid data folder collisions
- Fix ConsensusActionTests to use different data folders
- Give some RPC Tests more descriptive names

It appears we will now first have to look at NodeSettings and the circular references that will arise between the features using it and the feature references that it contains. That may overlap another issue: https://github.com/stratisproject/StratisBitcoinFullNode/issues/320

### CODE REVIEW

**Comment by bokobza** [comment]
I'll take care of this one today.

On 25 Aug 2017 05:30, "quantumagi" <notifications@github.com> wrote:

The main purpose of this PR is to create separate projects for 4 additional
features leaving 2 remaining featured (Consensus and Notifications):

   - Create separate projects for Wallet, MemoryPool, Miner and BlockStore
   (initial split) and update references
   - Update "appveryor.yml" and "build.sh" to include new test projects
   - Remove most feature dependencies from Stratis.Bitcoin.Tests
   (FullNodeBuilderTests)
   - Move tests to test projects and update namespaces
   - Fix data folder of BaseRPCControllerTest to avoid data folder
   collisions
   - Fix ConsensusActionTests to use different data folders
   - Give some RPC Tests more descriptive names

It appears we will now first have to look at NodeSettings and the circular
references that will arise between the features using it and the feature
references that it contains. That may overlap another issue: #320
<https://github.com/stratisproject/StratisBitcoinFullNode/issues/320>
------------------------------
You can view, comment on, or merge this pull request online at:

  https://github.com/stratisproject/StratisBitcoinFullNode/pull/370
Commit Summary

   - Create seperate projects for Wallet, MemoryPool, Miner and BlockStore

File Changes

   - *A* Stratis.Bitcoin.Features.BlockStore.Tests/Stratis.
   Bitcoin.Features.BlockStore.Tests.csproj
   <https://github.com/stratisproject/StratisBitcoinFullNode/pull/370/files#diff-0>
   (60)
   - *A* Stratis.Bitcoin.Features.BlockStore/Stratis.Bitcoin.
   Features.BlockStore.csproj
   <https://github.com/stratisproject/StratisBitcoinFullNode/pull/370/files#diff-1>
   (67)
   - *M* Stratis.Bitcoin.Features.IndexStore/Stratis.Bitcoin.
   Features.IndexStore.csproj
   <https://github.com/stratisproject/StratisBitcoinFullNode/pull/370/files#diff-2>
   (1)
   - *R* Stratis.Bitcoin.Features.MemoryPool.Tests/MempoolPersistenceTest.cs
   <https://github.com/stratisproject/StratisBitcoinFullNode/pull/370/files#diff-3>
   (2)
   - *A* Stratis.Bitcoin.Features.MemoryPool.Tests/Stratis.
   Bitcoin.Features.MemoryPool.Tests.csproj
   <https://github.com/stratisproject/StratisBitcoinFullNode/pull/370/files#diff-4>
   (57)
   - *R* Stratis.Bitcoin.Features.MemoryPool/MempoolFeature.cs
   <https://github.com/stratisproject/StratisBitcoinFullNode/pull/370/files#diff-5>
   (0)
   - *A* Stratis.Bitcoin.Features.MemoryPool/Stratis.Bitcoin.
   Features.MemoryPool.csproj
   <https://github.com/stratisproject/StratisBitcoinFullNode/pull/370/files#diff-6>
   (67)
   - *A* Stratis.Bitcoin.Features.Miner.Tests/Stratis.Bitcoin.
   Features.Miner.Tests.csproj
   <https://github.com/stratisproject/StratisBitcoinFullNode/pull/370/files#diff-7>
   (57)
   - *R* Stratis.Bitcoin.Features.Miner/MiningFeature.cs
   <https://github.com/stratisproject/StratisBitcoinFullNode/pull/370/files#diff-8>
   (0)
   - *A* Stratis.Bitcoin.Features.Miner/Stratis.Bitcoin.
   Features.Miner.csproj
   <https://github.com/stratisproject/StratisBitcoinFullNode/pull/370/files#diff-9>
   (68)
   - *M* Stratis.Bitcoin.Features.RPC.Tests/Controller/AddNodeActionTest.cs
   <https://github.com/stratisproject/StratisBitcoinFullNode/pull/370/files#diff-10>
   (4)
   - *M* Stratis.Bitcoin.Features.RPC.Tests/Controller/
   BaseRPCControllerTest.cs
   <https://github.com/stratisproject/StratisBitcoinFullNode/pull/370/files#diff-11>
   (3)
   - *M* Stratis.Bitcoin.Features.RPC.Tests/Controller/
   ConsensusActionTests.cs
   <https://github.com/stratisproject/StratisBitcoinFullNode/pull/370/files#diff-12>
   (26)
   - *M* Stratis.Bitcoin.Features.RPC.Tests/Controller/GetInfoActionTests.cs
   <https://github.com/stratisproject/StratisBitcoinFullNode/pull/370/files#diff-13>
   (2)
   - *M* Stratis.Bitcoin.Features.RPC.Tests/Controller/MempoolActionTests.cs
   <https://github.com/stratisproject/StratisBitcoinFullNode/pull/370/files#diff-14>
   (2)
   - *M* Stratis.Bitcoin.Features.RPC.Tests/Stratis.Bitcoin.
   Features.RPC.Tests.csproj
   <https://github.com/stratisproject/StratisBitcoinFullNode/pull/370/files#diff-15>
   (2)
   - *R* Stratis.Bitcoin.Features.Wallet.Tests/AccountRootTest.cs
   <https://github.com/stratisproject/StratisBitcoinFullNode/pull/370/files#diff-16>
   (2)
   - *R* Stratis.Bitcoin.Features.Wallet.Tests/HdAccountTest.cs
   <https://github.com/stratisproject/StratisBitcoinFullNode/pull/370/files#diff-17>
   (2)
   - *R* Stratis.Bitcoin.Features.Wallet.Tests/HdAddressTest.cs
   <https://github.com/stratisproject/StratisBitcoinFullNode/pull/370/files#diff-18>
   (2)
   - *R* Stratis.Bitcoin.Features.Wallet.Tests/Notifications/
   BlockObserverTest.cs
   <https://github.com/stratisproject/StratisBitcoinFullNode/pull/370/files#diff-19>
   (2)
   - *R* Stratis.Bitcoin.Features.Wallet.Tests/Notifications/
   TransactionObserverTest.cs
   <https://github.com/stratisproject/StratisBitcoinFullNode/pull/370/files#diff-20>
   (2)
   - *R* Stratis.Bitcoin.Features.Wallet.Tests/SpendingDetailsTest.cs
   <https://github.com/stratisproject/StratisBitcoinFullNode/pull/370/files#diff-21>
   (2)
   - *A* Stratis.Bitcoin.Features.Wallet.Tests/Stratis.Bitcoin.
   Features.Wallet.Tests.csproj
   <https://github.com/stratisproject/StratisBitcoinFullNode/pull/370/files#diff-22>
   (57)
   - *R* Stratis.Bitcoin.Features.Wallet.Tests/TransactionDataTest.cs
   <https://github.com/stratisproject/StratisBitcoinFullNode/pull/370/files#diff-23>
   (2)
   - *R* Stratis.Bitcoin.Features.Wallet.Tests/WalletControllerTest.cs
   <https://github.com/stratisproject/StratisBitcoinFullNode/pull/370/files#diff-24>
   (2)
   - *R* Stratis.Bitcoin.Features.Wallet.Tests/WalletHelpersTest.cs
   <https://github.com/stratisproject/StratisBitcoinFullNode/pull/370/files#diff-25>
   (2)
   - *R* Stratis.Bitcoin.Features.Wallet.Tests/WalletManagerTest.cs
   <https://github.com/stratisproject/StratisBitcoinFullNode/pull/370/files#diff-26>
   (2)
   - *R* Stratis.Bitcoin.Features.Wallet.Tests/WalletTest.cs
   <https://github.com/stratisproject/StratisBitcoinFullNode/pull/370/files#diff-27>
   (2)
   - *R* Stratis.Bitcoin.Features.Wallet.Tests/WalletTestBase.cs
   <https://github.com/stratisproject/StratisBitcoinFullNode/pull/370/files#diff-28>
   (2)
   - *R* Stratis.Bitcoin.Features.Wallet.Tests/WalletTestsHelpers.cs
   <https://github.com/stratisproject/StratisBitcoinFullNode/pull/370/files#diff-29>
   (2)
   - *R* Stratis.Bitcoin.Features.Wallet.Tests/WalletTransactionHandlerTest.
   cs
   <https://github.com/stratisproject/StratisBitcoinFullNode/pull/370/files#diff-30>
   (2)
   - *A* Stratis.Bitcoin.Features.Wallet/Stratis.Bitcoin.
   Features.Wallet.csproj
   <https://github.com/stratisproject/StratisBitcoinFullNode/pull/370/files#diff-31>
   (67)
   - *R* Stratis.Bitcoin.Features.Wallet/WalletFeature.cs
   <https://github.com/stratisproject/StratisBitcoinFullNode/pull/370/files#diff-32>
   (0)
   - *M* Stratis.Bitcoin.FullNode.sln
   <https://github.com/stratisproject/StratisBitcoinFullNode/pull/370/files#diff-33>
   (52)
   - *A* Stratis.Bitcoin.IntegrationTests/FullNodeTests.cs
   <https://github.com/stratisproject/StratisBitcoinFullNode/pull/370/files#diff-34>
   (54)
   - *M* Stratis.Bitcoin.IntegrationTests/Stratis.Bitcoin.IntegrationTests.
   csproj
   <https://github.com/stratisproject/StratisBitcoinFullNode/pull/370/files#diff-35>
   (5)
   - *M* Stratis.Bitcoin.Tests/BlockStore/BlockRepositoryInMemory.cs
   <https://github.com/stratisproject/StratisBitcoinFullNode/pull/370/files#diff-36>
   (2)
   - *M* Stratis.Bitcoin.Tests/BlockStore/BlockRepositoryTest.cs
   <https://github.com/stratisproject/StratisBitcoinFullNode/pull/370/files#diff-37>
   (4)
   - *M* Stratis.Bitcoin.Tests/BlockStore/BlockStoreBehaviorTest.cs
   <https://github.com/stratisproject/StratisBitcoinFullNode/pull/370/files#diff-38>
   (2)
   - *M* Stratis.Bitcoin.Tests/BlockStore/BlockStoreCachePerformanceCoun
   terTest.cs
   <https://github.com/stratisproject/StratisBitcoinFullNode/pull/370/files#diff-39>
   (2)
   - *M* Stratis.Bitcoin.Tests/BlockStore/BlockStoreCachePerformanceSnap
   shotTest.cs
   <https://github.com/stratisproject/StratisBitcoinFullNode/pull/370/files#diff-40>
   (2)
   - *M* Stratis.Bitcoin.Tests/BlockStore/BlockStoreCacheTest.cs
   <https://github.com/stratisproject/StratisBitcoinFullNode/pull/370/files#diff-41>
   (2)
   - *M* Stratis.Bitcoin.Tests/BlockStore/BlockStoreRepositoryPerformanc
   eCounterTest.cs
   <https://github.com/stratisproject/StratisBitcoinFullNode/pull/370/files#diff-42>
   (2)
   - *M* Stratis.Bitcoin.Tests/BlockStore/BlockStoreRepositoryPerformanc
   eSnapshotTest.cs
   <https://github.com/stratisproject/StratisBitcoinFullNode/pull/370/files#diff-43>
   (2)
   - *M* Stratis.Bitcoin.Tests/BlockStore/LoopTests/
   BlockStoreLoopIntegration.cs
   <https://github.com/stratisproject/StratisBitcoinFullNode/pull/370/files#diff-44>
   (3)
   - *M* Stratis.Bitcoin.Tests/BlockStore/LoopTests/
   BlockStoreLoopStepBaseTest.cs
   <https://github.com/stratisproject/StratisBitcoinFullNode/pull/370/files#diff-45>
   (3)
   - *M* Stratis.Bitcoin.Tests/BlockStore/LoopTests/
   BlockStoreLoopStepCheckNextChainedBlockExistStepTest.cs
   <https://github.com/stratisproject/StratisBitcoinFullNode/pull/370/files#diff-46>
   (2)
   - *M* Stratis.Bitcoin.Tests/BlockStore/LoopTests/
   BlockStoreLoopStepFindBlocksTaskTest.cs
   <https://github.com/stratisproject/StratisBitcoinFullNode/pull/370/files#diff-47>
   (2)
   - *M* Stratis.Bitcoin.Tests/BlockStore/LoopTests/
   BlockStoreLoopStepReadBlocksTest.cs
   <https://github.com/stratisproject/StratisBitcoinFullNode/pull/370/files#diff-48>
   (2)
   - *M* Stratis.Bitcoin.Tests/BlockStore/LoopTests/
   BlockStoreLoopStepReorganiseTest.cs
   <https://github.com/stratisproject/StratisBitcoinFullNode/pull/370/files#diff-49>
   (2)
   - *M* Stratis.Bitcoin.Tests/BlockStore/LoopTests/
   BlockStoreLoopStepTryPendingTest.cs
   <https://github.com/stratisproject/StratisBitcoinFullNode/pull/370/files#diff-50>
   (2)
   - *M* Stratis.Bitcoin.Tests/BlockStore/MemoryCacheStub.cs
   <https://github.com/stratisproject/StratisBitcoinFullNode/pull/370/files#diff-51>
   (4)
   - *M* Stratis.Bitcoin.Tests/Builder/FullNodeBuilderTest.cs
   <https://github.com/stratisproject/StratisBitcoinFullNode/pull/370/files#diff-52>
   (46)
   - *M* Stratis.Bitcoin.Tests/Stratis.Bitcoin.Tests.csproj
   <https://github.com/stratisproject/StratisBitcoinFullNode/pull/370/files#diff-53>
   (3)
   - *M* Stratis.Bitcoin.Tests/Utilities/NodeTcpListenerStub.cs
   <https://github.com/stratisproject/StratisBitcoinFullNode/pull/370/files#diff-54>
   (2)
   - *M* Stratis.Bitcoin/Features/Consensus/UnspentOutputs.cs
   <https://github.com/stratisproject/StratisBitcoinFullNode/pull/370/files#diff-55>
   (2)
   - *M* Stratis.Bitcoin/Features/MemoryPool/MempoolManager.cs
   <https://github.com/stratisproject/StratisBitcoinFullNode/pull/370/files#diff-56>
   (4)
   - *M* Stratis.Bitcoin/Features/MemoryPool/MempoolPersistence.cs
   <https://github.com/stratisproject/StratisBitcoinFullNode/pull/370/files#diff-57>
   (6)
   - *M* Stratis.Bitcoin/Features/MemoryPool/TxMemPoolEntry.cs
   <https://github.com/stratisproject/StratisBitcoinFullNode/pull/370/files#diff-58>
   (2)
   - *M* Stratis.Bitcoin/Features/Wallet/WalletManager.cs
   <https://github.com/stratisproject/StratisBitcoinFullNode/pull/370/files#diff-59>
   (4)
   - *M* Stratis.Bitcoin/Stratis.Bitcoin.csproj
   <https://github.com/stratisproject/StratisBitcoinFullNode/pull/370/files#diff-60>
   (4)
   - *M* Stratis.BitcoinD/Stratis.BitcoinD.csproj
   <https://github.com/stratisproject/StratisBitcoinFullNode/pull/370/files#diff-61>
   (3)
   - *M* Stratis.StratisD/Stratis.StratisD.csproj
   <https://github.com/stratisproject/StratisBitcoinFullNode/pull/370/files#diff-62>
   (4)
   - *M* appveyor.yml
   <https://github.com/stratisproject/StratisBitcoinFullNode/pull/370/files#diff-63>
   (4)
   - *M* build.sh
   <https://github.com/stratisproject/StratisBitcoinFullNode/pull/370/files#diff-64>
   (4)

Patch Links:

   - https://github.com/stratisproject/StratisBitcoinFullNode/pull/370.patch
   - https://github.com/stratisproject/StratisBitcoinFullNode/pull/370.diff

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/stratisproject/StratisBitcoinFullNode/pull/370>, or mute
the thread

**Comment by bokobza** [comment]
- The Stratis.Bitcoin.Features.BlockStore project seems to be empty and the Wallet, Miner and Mempool only have the Feature file in their respective projects. 
I'd rather Features are moved completely one after the other, with their tests to a different project, rather than creating empty projects for all of them at once.
What will happen if down the line you realize that one of them cannot be completely moved? 

- Also when you create new projects, please make sure that only the required nuget packages and references are used. 
The empty Blockstore project uses as many packages as the main project, while it should probably use none.

- one last thing: a PR like this could be split into a few commits where each one does 1 thing. A big commit including all the changes makes it more difficult to review and lessens the quality of the review.

**Comment by quantumagi** [comment]
As mentioned in the PR description the main goal is to create separate project files and also establish the anticipated dependencies. If any of those features can't be moved completely then we simply either don't move it completely or move the files back at that stage. Due to the the order not being all that easy to unravel it is makes life a heck of a lot easier to have all the projects on the ready to accept files and test what works... i.e. once we have everything in separate projects it would be easier to determine what we can move and when by simply moving files between these identical namespace in the project vs in Stratis.Bitcoin. I originally had these changes in a single commit as it seemed I would have to touch multiple places at once to be able to make progress. The PR as it is now represents a less ambitious version of that where the focus is only to create separate projects for now...

**Comment by bokobza** [comment]
I understand why you created these new projects now.
The RPC project has not moved completely either.

The problem is that it's confusing, and it makes the solution look unstable. 
Can't the wallet for example move to its own feature completely?

**Comment by quantumagi** [comment]
PosMinting is currently referencing the Wallet it from Stratis.Bitcoin

**Comment by bokobza** [comment]
Yeah indeed. what about the mining feature, can we extract it?

**Comment by quantumagi** [comment]
The Wallet has a dependency on the Miner so we can't leave the Wallet behind during such a move, otherwise Stratis.Bitcoin will be referencing features, and we can't have that.

**Comment by bokobza** [comment]
are you referring to this one `WalletRPCController : BaseRPCController`?
This belong to RPC rather than the wallet really.
I guess RPC will have a dependency on the wallet and quite a lot of other things.

Sorry I completely missed that : 
>  I also found that NodeSettings is tying features together. Was thinking of tackling that before continuing / completing this work. I think I've found a good approach for that. I anticipate we may find various similar issues which will make progress incremental...
> If you really feel it is confusing to move the code gradually then I can revert my work on this PR and retry from the Wallet angle or perhaps even start off with the NodeSettings changes...

I think if you can start over from the NodeSettings angle it'll give you a better view.
Also, you could move the WalletRPCController to the RPC stuff in your first commit, it needs to move.

**Comment by bokobza** [comment]
As agreed, the Wallet RPC controller does belong with the Wallet so it needs to stay where it is.
The method `generate` belongs with the mining stuff, and any dependency to the wallet should be removed. 
In particular, the wallet is used only to get a Script, so I suggested to pass the Script as input to the endpoint.
Then the wallet wouldn't be dependent on the Mining.
Please @quantumagi refer to this discussion on your next PR.

**Pull request closed without merging**
