### PR TITLE
[Wallet] Fix sent transactions not confirming

### PR DESCRIPTION
**Pull request by bokobza**
Rely on the spent transaction confirmation rather than on the receiving transaction confirmation to remove the output from the lookup table.

Related:
https://github.com/stratisproject/StratisBitcoinFullNode/issues/3107
https://github.com/stratisproject/StratisBitcoinFullNode/issues/3043

### CODE REVIEW

**Comment by bokobza** [comment]
@dangershony please run your manual tests for this.

**Comment by bokobza** [comment]
An explanation here for keen code reviewers:
When a transaction is sent by a wallet, a record of it is created in the wallet object called SpendingDetails and is attached to the output being spent.
so you have transactionOutput/spendingDetails. This spendingDetails object doesn't contains a block height at first, and when the transaction is mined, the block is received by the wallet manager who then adds the block height to the spendingDetails object.

To make sure that outputs and addresses are quickly searched through, we maintain lookup objects. When a transaction is spent, we remove it from the "outputs that can be spent" lookup.

The problem here was that, by mistake, when a transaction was sent and added to the wallet object, we looked at whether the output being spent was confirmed (which is almost always is) and then remove the output from the lookup. subsequently when a mined block would arrive with the transaction in it, the block height would never get added to the spendingDetails and the spent output would always be marked as unconfirmed.

**Comment by einewton** [comment]
This still does not resolve #3043 - Loading my wallet with a lot of stakes, and also, I still cannot see my initial deposit in the history with the wallet having the issue.

**Comment by dangershony** [comment]
This was already included in another PR

**Pull request closed without merging**
