### PR TITLE
Stubs for mempool validator tests

### PR DESCRIPTION
**Pull request by mikedennis**
- Moved mempool unit tests to appropriate folder location/namespace inline with testing standards (caused some changes to other files do to usings being slightly different)
- Created test stubs for ~45 tests for testing different mempool validator scenarios. Added some comments about how to potentially test.

### CODE REVIEW

**Comment by bokobza** [comment]
I'll take this one.

**Comment by bokobza** [comment]
Good work on the stubs.
Do you need to add the "Bitcoin" to these objects' types? Does it not work without?
Like in  "internal static **Bitcoin**.Features.Wallet.Wallet CreateWallet(string name)"

**Comment by mikedennis** [comment]
Problem is there is a parallel "Features" namespace in the test project now so dropping Bitcoin is ambiguous. I think probably could fix it by getting rid of the fully qualified name, and have a using instead. I could give that a try if that's preferred?

**Comment by bokobza** [comment]
ah ok. :-)
either using the full namespace (quite long), or what you suggested.
I mean it's personal preference and I was surprised to see something starting with Bitcoin.
No big deal anyway, so if it's not too much trouble, try to see what's more pleasing and I'll take that.

**Comment by bokobza** [comment]
also there is a file conflict that needs addressing.

**Comment by mikedennis** [comment]
Sure thing. I prefer using short names with using (instead of fully qualified) and only qualifying them if there is a conflict, so I will give that a try. Maybe there was a reason for that in the first place I don't know about but will give it a try. Also will sort out that conflict. Thanks!

**Comment by mikedennis** [comment]
Ok I see now why the namespace is fully qualified. There is a conflict with that same interface, IBlockRepository, in NBitcoin that's why it was fully qualified. I think it's probably best to leave it as is as a lot less references to it than NBitcoin objects.

**Comment by bokobza** [comment]
ah yes indeed. 
Cool I'm happy with that. Are you done with this change?

**Comment by mikedennis** [comment]
Yes I am. Thanks Jeremy!

**Pull request merged**
