### PR TITLE
Rooted datadir

### PR DESCRIPTION
**Pull request by bokobza**
This is in relation to https://github.com/stratisproject/StratisBitcoinFullNode/pull/1308 and https://github.com/stratisproject/StratisBitcoinFullNode/issues/1307.
@Aprogiena

### CODE REVIEW

**Comment by Aprogiena** [comment]
I'm not sure about the changes in the tests, I am not familiar with those tests. But the main change looks good, makes perfect sense. However, no tests from me, so someone should check that it fixes the problem.

**Comment by bokobza** [comment]
The problem was that since we didn't have a property giving the root path of DataFolder, people used other values that happens to be the same, like AddressManagerFilePath.
So I added a root path and fixed the tests.

**Comment by bokobza** [comment]
@monsieurleberre @ferdeen @majikandy can one of you please have a look at this?

**Comment by majikandy** [comment]
Looks fine to me

**Comment by bokobza** [comment]
cool stuff, thanks guys.

**Pull request merged**
