### PR TITLE
Signalr port foreach network

### PR DESCRIPTION
**Pull request by ianadavies**
This PR adds a different default SignalR port for each network. This allows us to run multiple Wallets at the same time with SignalR

### CODE REVIEW

**Comment by dangershony** [comment]
Why not use the API port? what is the logic behind exposing two self host servers on the FN can SingalR not live along side the API?

**Comment by fenix2222** [comment]
SignalR is a separate feature that can run independently of the API and RPC, so we shouldn't couple it with API hosted service. It is a first-class citizen unless I misunderstood the concern

**Comment by dangershony** [comment]
That is a good argumet, but I don't agree so much.

Consider though It can be a separate feature and still relay (or have a dependecny) on the api host.
Is there realistically ever a case where SignalR is used and api is not needed? 

The api feature does not carry business logic most of the logic is put in the dedicated features and controllers are discoverale
The SignalR feature seems to me to have cross feature logic (wallet, mining etc...) when such logic should be probably implemented in the appropirate features and the SignalR freamork would go in the api feature. Basically what I am saying is the design is not modular (you cannot ship signalr without a wallet, but you can ship api as standalone) 

API feature should probably be called ServerFeature and it allow web api and SignalR freaworks the business logic would be then contained to the features (WalletController lives in wallet feature so SignalR wallet event should as well)

Also how it is implemented in the program.cs file is not the best, the logic should be hiddenin the feture itself (ideally)

**Comment by fenix2222** [comment]
> you cannot ship signalr without a wallet

I do not agree with this. You can have signalr without the wallet or any other features. It can relay any messages from the node, doesn’t have to be wallet specific message. It can be used by any type of the client app. One good example could be a dashboard app that you may want to show some stats from the node. Basically instead of polling nodes API, you could just subscribe to signalr events. It can easily subscribe to node events from ISignals bus we have.

**Comment by dangershony** [comment]
>I do not agree with this. You can have signalr without the wallet or any other features like API.

This looks to me like a hard dependency on the wallet feature
https://github.com/stratisproject/StratisBitcoinFullNode/pull/3901/files?file-filters%5B%5D=.csproj#diff-fe051c296d9510ad7e513a360ef65184R14

And it seems to me you are one of the approvers not making what you claim even possible without a refactor of SignalR  
https://github.com/stratisproject/StratisBitcoinFullNode/pull/3901#pullrequestreview-278137970

The rest I agree though you would have to implement what I described above to achive it.

**Comment by fenix2222** [comment]
> This looks to me like a hard dependency on the wallet feature 

Sure, atm it has a dependency, but we can change this in the future once we have a requirement to make it available to other types of clients. My main point is that SignalR is a standalone feature that should be defined as a "Feature". Similar to how RPC is a feature and has a dependency on "Consensus" feature or like PoA feature that has a dependency on "Consensus" and "Miner" features.

Currently, it makes it possible for us to still run SignalR feature without having a dependency on API or RPC and have various types of client apps, that do not need to query node and only listen to events.

**Comment by MithrilMan** [comment]
In my view SignalR should just relay event-bus events to the outside world, it doesn't need to know any specific message, so it doesn't need any reference to any specific feature

why did we have hard dependency actually?

FullNode shouldn't have a known concept of SignalR , just the concept of event bus, and signalr is just a way to relay a subset of these events to interested parties
consider it like hooking into fullnode process to collect information and push them outside (in an async way so that it doesn't impact on fullnode performance)

**Comment by MithrilMan** [comment]
I see why we had the Wallet referenced, because we were doing something like
`public class StakingInfoClientEvent : GetStakingInfoModel, IClientEvent`

If we want SignalR to be just a relay of events, we should handle events in json or something like that, not defining a type for every kind of events we want to send with SignalR

**Comment by dangershony** [comment]
>Sure, atm it has a dependency, but we can change this in the future once we have a requirement

You will never have a requirement for modularity on the contrary you will just build more stuff in to the signalr feature and it will become almost impossible to refactor it later, you have to build the feature form the start without dependencies. 

>Similar to how RPC is a feature and has a dependency on "Consensus"  

RPC is a very bad example and I would not compare to RPC, that is a bit special because we just wanted to support Bitcoin Cores (or StratisX) RPC, better compare to API where there is only a dependency to Stratis.Bitcoin.

>SignalR is another medium for communicating with the server-side, like API and RPC, why would we want to couple it?  

Come to think about it API is a bad name to the current API feaure, perhaps it sould be called WebServer feature and it would be enabled such
```
 nodeBuilder
 .UsePowConsensus()
 .UseWallet()
 .EnableWebServer()
```

`EnabledWebServer()` will create a self host server and discover controllers (and maybe also signalr evetns)

**Pull request merged**
