### PR TITLE
Src folder

### PR DESCRIPTION
**Pull request by dangershony**
Moving all the source code in to the src folder.

### CODE REVIEW

**Comment by Aprogiena** [comment]
You forgot about appveyor ... but let's say we can fix that later

**Comment by bokobza** [comment]
@dangershony you rolled back NStratis to the 13th October with this change.

**Comment by Aprogiena** [comment]
hmm, that is not necessarily a bad thing after all. it seems like the changes done after that introduced some problems in the Node that some people on slack reported, including for example #695

**Comment by Aprogiena** [comment]
The above seems not entirely correct, at least #679 exists even with the current master. But I can see one race condition being reverted in the code by this.

**Pull request merged**
