### PR TITLE
Re-apply mempool transactions on startup

### PR DESCRIPTION
**Pull request by quantumagi**
https://dev.azure.com/Stratisplatformuk/StratisBitcoinFullNode/_workitems/edit/4543/

### CODE REVIEW

**Comment by quantumagi** [comment]
This PR is not high priority but could form the basis of a solution if any mempool related issues are discovered. It does add the benefit of only processing transactions for the wallets to which they apply.

**Comment by codingupastorm** [comment]
Keen for the mempool fixes, they should put the node in a state where mempool always matches the wallet. 

Unsure about the `GetAffectedWallets` code. Feels like an optimisation that might be better as its own PR, and that we don't know if it is actually faster yet.

**Comment by quantumagi** [comment]
Those are not unrelated changes. They address inefficiencies in the methods used for this PR.

**Comment by quantumagi** [comment]
@fassadlr , you have removed the `TODO`. Was that your intention?

**Comment by fassadlr** [comment]
> @fassadlr , you have removed the `TODO`. Was that your intention?

Hi @quantumagi, yes it is intentional. I will create a PR from the removed code after release.

**Comment by codingupastorm** [comment]
The 3 scenarios I know of that we should test, manually or otherwise:
When the mempool contains transactions from the wallet:
- Node starts with a mempool.dat it didn't know it had.
- Node starts missing a mempool.dat that it previously had.
- Node starts with a mempool.dat that it previously had, aka normal operation

**Comment by codingupastorm** [comment]
I manually tested the above 3 scenarios and everything seems to work well.

**Pull request merged**
