### PR TITLE
Merge NBitcoin fix for MacOSX buffer sizes

### LINKED ISSUE #1173: [Node] check if problem on Mac OS is relevant to us
We need to check with load is affected by similar issue is discussed here:
https://github.com/MetacoSA/NBitcoin/issues/345
https://github.com/MetacoSA/NBitcoin/commit/6ae1452e8e5252f3ea7aee3028d882199fe8e66a

### PR DESCRIPTION
**Pull request by mikedennis**
Reference NBitcoin commit:

https://github.com/MetacoSA/NBitcoin/commit/6ae1452e8e5252f3ea7aee3028d882199fe8e66a

Fixes #1173

### CODE REVIEW

**Comment by mikedennis** [comment]
Please don't merge yet - going to run some tests first. I've got my strat testnet node running this branch right now. So far so good... running about 500MB memory and connected to several peers. I will check it in the morning.

**Comment by bokobza** [comment]
Are you going to test on a Mac?

**Comment by dangershony** [comment]
What if we use compile arguments?

**Comment by bokobza** [comment]
or just do an if(Mac) etc...

**Comment by dangershony** [comment]
Yeah that will work @bokobza

**Comment by mikedennis** [comment]
So windows node didn't do anything horrible. Still churning along at ~515MB memory. Will be very difficult to tell performance difference on a running node - too many variables. I believe nopara wrote some sort of test to test this originally in NBitcoin, so was going to take a look at that and see if I can use something similar to do some testing.

I don't have a Mac to test with but was going to see if I could find a VM or something somewhere. I have an Unbuntu and a RPI but no Mac. Maybe I could see if I could get a volunteer from discord.

Do we want to do the conditional compile for Mac? Or just make sure it doesn't do anything bad to the other OSs?

**Comment by bokobza** [comment]
How about this @Aprogiena @mikedennis @dangershony ? Minimum impact.

```
if (RuntimeInformation.IsOSPlatform(OSPlatform.OSX))
{
    // Use max supported by MAC OSX Yosemite/Mavericks/Sierra (https://fasterdata.es.net/host-tuning/osx/)
    this.ReceiveBufferSize = 1048576;
    this.SendBufferSize = 1048576;
}
else
{
   this.ReceiveBufferSize = 1000 * 5000;	 
   this.SendBufferSize = 1000 * 1000;
}
```

**Comment by dangershony** [comment]
This looks good to me @bokobza 
@mikedennis please updated the PR.

**Comment by Aprogiena** [comment]
that's ugly af

**Comment by bokobza** [comment]
The Mac build failed (how fitting!) so I've restarted it.

**Pull request merged**
