### PR TITLE
Add missing command line help

### PR DESCRIPTION
**Pull request by quantumagi**
See https://dev.azure.com/Stratisplatformuk/StratisBitcoinFullNode/_workitems/edit/3203.

### CODE REVIEW

**Comment by quantumagi** [comment]
The help being displayed is dependent on the daemon being run.

**Comment by dangershony** [comment]
This should go in branch 3.0.3 as well

**Comment by quantumagi** [comment]
I assume that would happen after PR testing?

**Comment by quantumagi** [comment]
Worked with Maciej to add this to 3.0.3.

**Pull request merged**
