### PR TITLE
[Activation] Merge from master

### PR DESCRIPTION
**Pull request by bokobza**
I need @codingupastorm @rowandh @ferdeen @mikedennis and @kogot to look at this as it's their code that has moved to the activation branch.

@noescape00 @fassadlr The code compiles, that's all I can say.

### CODE REVIEW

**Comment by codingupastorm** [comment]
Have reviewed:
* SmartContractPosRegTest.cs

LGTM!

**Comment by kogot** [comment]
Reviewed. @bokobza 
All my changes in the file: Stratis.Bitcoin.Features.Miner/Staking/PosMinting.cs have discarded.
For example line 361, 369, 637, 648, 660, 1047
File: Stratis.Bitcoin.Features.Miner/Models/GetStakingInfoModel.cs is Ok

**Comment by fassadlr** [comment]
@bokobza , I concur with @codingupastorm! Looks good to me :)

**Comment by bokobza** [comment]
@kogot I've updated your changes.

**Comment by kogot** [comment]
@bokobza Looks good now, thanks.

**Comment by ferdeen** [comment]
@bokobza Checked the WalletSync work (#1890) against this commit and all looks good.  Cheers.

**Comment by bokobza** [comment]
@noescape00 feel free to merge if you're happy.

**Pull request merged**
