### PR TITLE
[API] Start api earliest

### PR DESCRIPTION
**Pull request by fassadlr**
The fix here is to call `UseBaseFeature` explicitly.

### CODE REVIEW

**Comment by fassadlr** [comment]
I tested this with all the daemons and integration tests.

**Comment by MithrilMan** [comment]
Sure, as I pointed out at the end of this comment 
https://github.com/stratisproject/StratisBitcoinFullNode/issues/3021#issuecomment-453057080

this is the easier fix atm (that I still consider a workaround because requires users to build the node this way, plus actually we are breaking some other users codebase because now they need to explicitly call UseBaseFeature too so we have to state this somewhere) of course, but if it serves for the purpose then I'm fine with this

**Comment by fassadlr** [comment]
@MithrilMan I agree with you, however I feel that we either go with the approach of calling EVERY component explicitly or we have to refactor how the node starts.

Currently, hiding a call to `UseBaseFeature` in `NodeSettings` doesn't feel right. This why we can argue that each daemon must call `UseNodeSettings` as well? ;) 

Programmatically, we can start the node without calling `UseNodeSettings` but it will fail. The same with this now, we CAN call the node without `UseBaseFeature` but it will not work (obviously).

To me this change isn't architecturally wrong, its just that we need to now remember to call it every time.

**Comment by MithrilMan** [comment]
I didn't said it's wrong, but it's something we should state somewhere on the update because will break any daemon someone has already built.

Btw I think you forget to remove implicit UseBaseFeature from here:
https://github.com/stratisproject/StratisBitcoinFullNode/blob/a414163ca2be8e63b24003d537b562c55084ed7e/src/Stratis.Bitcoin/Builder/FullNodeBuilder.cs#L90-L91

**Comment by dangershony** [comment]
@fassadlr and I agreed that a less invasive way would be to introduce a flag to a feature that signal to the startup code to tart that feature before BaseFeature.

A new PR will be created.

**Pull request closed without merging**
