### PR TITLE
Don't wait for peers when minting new POS block.

### LINKED ISSUE #403: [POS] Block rejected by peers
If at least one peer does not accept our new block in 100 seconds, we lost 100 seconds of mining, then we raise exception and start over. This should be optimized.

### PR DESCRIPTION
**Pull request by mikedennis**
Fixes #403

### CODE REVIEW

**Comment by dangershony** [comment]
Hi @mikedennis looks good did you try to mint?

**Comment by mikedennis** [comment]
@dangershony I got some advice from apro and going to get setup to do some POS minting to verify this works. Hold off merging until I can confirm it doesn't break anything.

**Comment by dangershony** [comment]
@mikedennis are you happy with this change now?

**Comment by mikedennis** [comment]
Not sure, had this error. It doesn't seem related #554

**Comment by Aprogiena** [comment]
This one is #500, fixed by my next PR. #554 does not seem related, but it seems quite new.

**Comment by Aprogiena** [comment]
OK, 554 is also not related.

**Comment by mikedennis** [comment]
I can no longer make #554 happen but had #500 (previous block unexpected hash) happen several times.

**Comment by dangershony** [comment]
ok i think I will merge this, it is indeed not related to #554

**Comment by dangershony** [comment]
FYI I think this line can now be removed
```
 this.blockRepository.PutAsync(context.BlockResult.ChainedBlock.HashBlock, new List<Block> { block }).GetAwaiter().GetResult();
```
This signaler will not relay to peers until a block is persisted to store.
I will fix that when I do the consensus fix

**Pull request merged**
