### PR TITLE
[FS] Fix for NullReferenceException for MempoolSignaled async loop

### PR DESCRIPTION
**Pull request by fenix2222**
Code to handle peers that may not have mempool behavior registered

### CODE REVIEW

**Comment by zeptin** [comment]
How does this happen? The mempool behaviour should be in the list of template behaviours that get attached to every peer on connection?

**Comment by fenix2222** [comment]
This is the line where nullreferenceexception happens, so I guess if node is not using `UseMempool` it can happen. The logs a very limited

**Comment by zeptin** [comment]
Hmm, actually, I think this probably happens when a peer is being disconnected.

Probably a race condition something like the following:

1. `this.connection.ConnectedPeers;` gets assigned to `peers`
2. A peer gets disconnected elsewhere & behaviour detachment starts. The mempool behaviour for that peer gets disposed
3. `peers` gets enumerated, causing the exception

**Comment by fenix2222** [comment]
That would definitely explain it. The code change should handle it though

**Pull request merged**
