### PR TITLE
Update NBitcoin part 1

### PR DESCRIPTION
**Pull request by mikedennis**
Update NBitcoin to 4.0.0.39

These commits were not merged:
https://github.com/MetacoSA/NBitcoin/commit/d8ea26e205d1c96eecdc0dd0c319d9765b75a856
https://github.com/MetacoSA/NBitcoin/commit/a19f006ee7da2ee40fd89d325fa589de971f7632
https://github.com/MetacoSA/NBitcoin/commit/dcb47ab4b7573e4df25f8f0a84a455adf3d3dce5
https://github.com/MetacoSA/NBitcoin/commit/dfe386af569fe4811565e826a73e7edf79568b87
https://github.com/MetacoSA/NBitcoin/commit/56bfd1cbca535424b160d8a40688a79de4800630
https://github.com/MetacoSA/NBitcoin/commit/d1bd95e29c621ebcd3e2f233274887583184543c
https://github.com/MetacoSA/NBitcoin/commit/66b2839a72bd8b9aa8372ecdecb46408f9962335
https://github.com/MetacoSA/NBitcoin/commit/3ecb770990cb27ed9f8962e2fd7f2c05e689776f
https://github.com/MetacoSA/NBitcoin/commit/d6e603aabbb87aead26a65af2a6a19ed20a5c9ab
https://github.com/MetacoSA/NBitcoin/commit/bcffb1d730446828a33831d4524ca81ce2d22e8c
https://github.com/MetacoSA/NBitcoin/commit/1cfd80660f85cbeff4df7f3f9e5a60594eaacc5d

These commits were merged:
https://github.com/MetacoSA/NBitcoin/commit/fbaafcf24da4b891dc32b0184f937b739700cde8
https://github.com/MetacoSA/NBitcoin/commit/85702a36be7cb30a5c45a4d4e047b82e09e0a05a
https://github.com/MetacoSA/NBitcoin/commit/a46c5d053bf87a0c53aa670f42c7e274b5bf219e
https://github.com/MetacoSA/NBitcoin/commit/e2bfbee34c2e39952b6c06e9d7636e9500dfca57
https://github.com/MetacoSA/NBitcoin/commit/8340b14b83dbc1f7fb2e6d50a11ccd6f3c156fe3

Partially address issue #1008 

Please verify there is nothing in the not merged list that we may need.

### CODE REVIEW

**Comment by dangershony** [comment]
I will have a look at this thank you Mike

**Comment by dangershony** [comment]
Hi mike how did you add the NBitcoin commits to the current PR I wonder? its different repos 🙃

**Comment by mikedennis** [comment]
Hi Dan, I manually merged them by looking at the commit changes from the NBitcoin repo. I didn't see any other easy way of doing it. Fortunately most of them are fairly small changes so it's not too difficult.

**Comment by dangershony** [comment]
What about adding
https://github.com/MetacoSA/NBitcoin/commit/56bfd1cbca535424b160d8a40688a79de4800630

**Comment by dangershony** [comment]
@mikedennis I will merge this, see my comments perhaps we should consider the two additional PRs?

**Pull request merged**
