### PR TITLE
[Indexer] Remove unused method from the address indexer

### PR DESCRIPTION
**Pull request by fassadlr**
This is for the next release.

### CODE REVIEW

**Comment by noescape00** [comment]
Please dont remove getaddressbalances. 
Why?

**Comment by fassadlr** [comment]
> Please dont remove getaddressbalances.
> Why?

Isn't it obvious from the heading of the PR?

**Comment by noescape00** [comment]
>Isn't it obvious from the heading of the PR?

It was more of a rhetorical question

This method will be 100% needed for exchanges integration. It is exposed on API. No need to delete it just because none of our own code uses it.

**Comment by fassadlr** [comment]
> > Isn't it obvious from the heading of the PR?
> 
> It was more of a rhetorical question
> 
> This method will be 100% needed for exchanges integration. It is exposed on API. No need to delete it just because none of our own code uses it.

Why didn't you just explain that in the first place?

I will close this PR and add a comment that explains this.

**Comment by noescape00** [comment]
>Why didn't you just explain that in the first place?

Sorry, I thought I've mentioned it before at some point. 

>I will close this PR and add a comment that explains this.

Thanks, mate!

**Pull request closed without merging**
