### PR TITLE
[FN] Set the Block.BlockSize property only on first serialization

### PR DESCRIPTION
**Pull request by dangershony**
This supersedes 
https://github.com/stratisproject/StratisBitcoinFullNode/pull/3942

To ensure the BlockSize is set only once with the correct deserialization parameters.

### CODE REVIEW

**Comment by dangershony** [comment]
Yeah I will fix the tests now.

What we need is first consistency and second to have the true value of the block size.
It's possible to calculate the block size without relaying on the BlockSize property (for other cases like the block size rule)

My change introduces consistency however it may in some cases not capture the real block size (in case serialization is done first with different Options param

I'd say this is the best e can achieve without too much refactoring.

**Comment by dangershony** [comment]
@zeptin this seems fine now

**Comment by fassadlr** [comment]
@dangershony pardon my ignorance but I'm still a bit unsure as to why this change is needed? What is the issue with setting the block size again after serializarion?

**Comment by dangershony** [comment]
>What is the issue with setting the block size again after serializarion?
When you serialize with segwit options and without segwit options you get different results of the block size (segwit is an exmapl we may have other things that determine serialization)

So this PR will capture the first size which should be the correct one as it gets des from the network.

**Pull request merged**
