### PR TITLE
Change ports

### PR DESCRIPTION
**Pull request by nopara73**
5000 -> 37220  
5105 -> 37221  
Tied to: https://github.com/stratisproject/Breeze/pull/242
Resolves: https://github.com/stratisproject/Breeze/issues/240

### CODE REVIEW

**Comment by dev0tion** [comment]
Please ping me on merge @nopara73, I need to change that in the UI as well.

**Comment by nopara73** [comment]
@dev0tion  I did change the UI as well: https://github.com/stratisproject/Breeze/pull/242

**Comment by dangershony** [comment]
Lets try to get this in asap

**Comment by bokobza** [comment]
that's cool, thanks @nopara73

**Pull request merged**
