### PR TITLE
Propagate tx to 100% of the peers for the full node.

### PR DESCRIPTION
**Pull request by noescape00**
For the full node (where we have consensus and can validate the tx) changed propagation from 50% of the peers to 100%. 

Fix: #973

### CODE REVIEW

**Comment by fassadlr** [comment]
@noescape00 This scenario calls for an abstract method to be implemented. I really don't like when booleans are used in this way as it's not explicit as to what the meaning of the boolean is or what it is used for.

Seeing that `BroadcasterManagerBase` is abstract, why not define an abstract method called `OnPropagateTransactionToPeersAsync` and implement the propagation to peers in `FullNodeBroadcasterManager` and `LightWalletBroadcasterManager`. So in FullNode we do all of them and in LightWallet only half. 

So in PropagateTransactionToPeersAsync you would go:

```
protected async Task PropagateTransactionToPeersAsync(Transaction transaction)
{
    this.AddOrUpdate(transaction, State.ToBroadcast);
    var invPayload = new InvPayload(transaction);
    var peers = this.connectionManager.ConnectedNodes.ToList();

    OnPropagateTransactionToPeersAsync();
}
```

And in FullNode's implementation of OnPropagateTransactionToPeersAsync():

```
    int propagateToCount = peers.Count;

    for (int i = 0; i < propagateToCount; ++i)
        await peers[i].SendMessageAsync(invPayload);
```

What do you think?

**Comment by noescape00** [comment]
>What do you think?

Absolutely agree. Just wanted to separate refactoring from the algho changes.
Will do this in this PR then.

**Comment by fassadlr** [comment]
> Will do this in this PR then.

Awesome 👍

**Comment by noescape00** [comment]
I guess a cleaner solution is to pass the peers to 'PropagateTransactionToPeersAsync'. 
Otherwise if we implement 'OnPropagateTransactionToPeersAsync' for both light and full nodes we will have a lot of copy pasted code which I'd really like to avoid.

**Comment by fassadlr** [comment]
Thats true, OK how about just implementing an abstract property call PeerPropagationCount and implement in each class? The property will just return the amount of peers to propagate to.

**Comment by noescape00** [comment]
>Thats true, OK how about just implementing an abstract property call PeerPropagationCount and implement in each class? The property will just return the amount of peers to propagate to.

It's good for now but we will have to refactor it soon. 
There was an issue about propagating txes to the IBD peers so in the future we will have to sort the peers by .IsSynced for the light node so we always prioritize peers that are not in IBD. 
So I'd better just pass a list with the peers we'd like to propagate to and let LWBM and FNBM decide what peers to select for the propagation.

**Comment by noescape00** [comment]
>Good job on the refactor dude. Looks much cleaner now!

Thank you for the review! =)

**Pull request merged**
