### PR TITLE
Add Fody weaving to feature projects

### LINKED ISSUE #2697: [Logging] Fody does not weave the features
During testing it has become apparent that the feature projects (e.g. mempool, wallet) do not have entry/exit trace logs.

`FodyWeavers.xml` seems to imply that they should:

`<TraceOn namespace="Stratis.Bitcoin+*" class="private" method="private" />`

Upon further experimentation, the `Tracer.Fody` nuget package needs to be added to every csproj that we want to be weaved. I also added a reference to the `FodyNlogAdapter` project to the feature project I was testing, but I am not 100% sure if both are required.

Therefore, someone needs to go through all the feature projects and add these references so that we get adequate trace logging for them.

### PR DESCRIPTION
**Pull request by zeptin**
Fixes #2697 

Fody all the things

### CODE REVIEW

**Comment by zeptin** [comment]
@maciejzaleski @ArcSin2000X Note that this PR may substantially increase the size of the trace logs getting generated.

**Comment by dangershony** [comment]
Do we need to add logs on all these projects?
@bokobza @fassadlr 

Perhaps yes, we do.

**Comment by zeptin** [comment]
At the very least we need wallet logs to determine whether the wallet reorg bug is related to the node reorg bug or not.

My feeling is that we removed entry/exit logs everywhere under the expectation that Fody would provide them going forwards, so we should add it to all the features. If there are particularly noisy method calls (and there will be, almost certainly) we can `[NoTrace]` them.

**Comment by dangershony** [comment]
ok perhaps its true, FYI what wallet reorg bug?

**Comment by zeptin** [comment]
@dangershony #2676

**Comment by bokobza** [comment]
From here, it might be preferable if the SC team did it themselves: https://github.com/stratisproject/StratisBitcoinFullNode/pull/2250#discussion_r220107454

So maybe remove Fody from the SC feature.
Also, what about entry/exit logs? Are they all gone from the features? Also, did you add [NoTrace] to the methods that are called too often?

**Comment by zeptin** [comment]
Many of the consensus rules should probably also be squelched but this PR is getting large enough as it is.

**Comment by bokobza** [comment]
I'm happy with the PR so far, but I'm just afraid the quantity of logs is going to be really huge if we don't really do all the methods that are called often.
Maybe just concentrate on the feature you need to see logs for first?

**Pull request merged**
