### PR TITLE
[Dashboard] Added whole bunch of null reference checks

### PR DESCRIPTION
**Pull request by fenix2222**
Added null reference checks to make sure dashboard doesn't crash
This is just a quick fix - more PRs to follow

### CODE REVIEW

**Comment by noescape00** [comment]
Based on the info I heard on standup I'm more in favor of changing the design so we keep our view of the node and update it using the API instead of pulling all the data when we display dashboard.

**Comment by fenix2222** [comment]
It definitely needs a redesign, this is just to get it running for now as users are having problems running this dashboard.

**Comment by fenix2222** [comment]
After some discussion with the team, we will keep adding to this branch to get dashboard voting also working, so for now, do not merge

**Comment by fassadlr** [comment]
Closing as dashboard is now in its own project :)

**Comment by fassadlr** [comment]
See https://github.com/stratisproject/StratisMasternodeDashboard

**Pull request closed without merging**
