### PR TITLE
PoA miner settings for bootstrapping

### PR DESCRIPTION
**Pull request by noescape00**

### CODE REVIEW

**Comment by justintopham** [comment]
> this.settings = new PoAMinerSettings(nodeSettings);

MinerSettings added as a singleton as part of the Mining feature...

>                    if (((this.ibdState.IsInitialBlockDownload() || !this.connectionManager.ConnectedPeers.Any()) && !this.settings.BootstrappingMode)
	                        || !this.federationManager.IsFederationMember)
This will work _although_ if you leave IsInitialBlockDownload() as it was (out of the brackets), it means you have to give an up-to-date genesis block timestamp - with this the timestamp you give doesn't matter.

> // Don't mine in IBD in case we are connected to any node.

Comment out of date

**Comment by dangershony** [comment]
@noescape00 Seems there is an issue with the tests

**Comment by noescape00** [comment]
>MinerSettings added as a singleton as part of the Mining feature...

And also it is created in several places. 
Good catch, I'll put it on DI everywhere for consistency. 

>Comment out-of-date

Fixed

**Comment by noescape00** [comment]
>@noescape00 Seems there is an issue with the tests

Fixed

**Pull request merged**
